"""Shared helpers for the Ukiyo-e verification suite."""

import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path

sys.dont_write_bytecode = True

REPO = Path(__file__).resolve().parents[1]
GENERATED_PATHS = (
    "lua/ukiyo_e/palette.lua",
    "tmux/colors.conf",
    "tmux/status.conf",
    "tmux/status-plain.conf",
    "gnome-terminal/palette.sh",
)
HEADER_LUA = (
    "-- GENERATED by scripts/generate.py from palette.toml."
    " Do not edit by hand."
)
HEADER_SH = (
    "# GENERATED by scripts/generate.py from palette.toml."
    " Do not edit by hand."
)
SEED_HASH = "bb85e4bfc8d89b0e62c8fa53ccdd13d12e2f77b3"
IGNORED_COPY = shutil.ignore_patterns(".git", "__pycache__")


@dataclass(frozen=True)
class RunResult:
    """Exit code and captured text of one finished process."""

    code: int
    stdout: str
    stderr: str


def run(argv, cwd=None, env=None, stdin=None):
    """Run a command and capture its text output."""
    proc = subprocess.run(
        argv,
        cwd=cwd,
        env=env,
        input=stdin,
        capture_output=True,
        text=True,
        check=False,
    )
    return RunResult(proc.returncode, proc.stdout, proc.stderr)


def scratch_dir():
    """Create a fresh directory under TMPDIR (the session scratchpad)."""
    return Path(tempfile.mkdtemp(prefix="ukiyo_e_"))


def copy_repo():
    """Copy the working tree (without .git) into a scratch directory."""
    target = scratch_dir() / "repo"
    shutil.copytree(REPO, target, ignore=IGNORED_COPY, symlinks=True)
    return target


def remove_tree(path):
    """Delete a scratch tree created by this suite."""
    shutil.rmtree(Path(path).parent, ignore_errors=True)


def remove_dir(path):
    """Delete a scratch directory created by scratch_dir()."""
    shutil.rmtree(path, ignore_errors=True)


def generate(root, *args):
    """Run the generator of a repository copy."""
    script = Path(root) / "scripts" / "generate.py"
    return run([sys.executable, str(script), *args], cwd=root)


def generated_hashes(root):
    """Map every generated path to the SHA-256 of its bytes."""
    hashes = {}
    for rel in GENERATED_PATHS:
        data = (Path(root) / rel).read_bytes()
        hashes[rel] = hashlib.sha256(data).hexdigest()
    return hashes


def load_palette_toml(root=REPO):
    """Parse palette.toml of a repository tree."""
    with open(Path(root) / "palette.toml", "rb") as handle:
        return tomllib.load(handle)


def resolve_ref(doc, value):
    """Resolve a [terminal]/[tmux] value to lowercase hex."""
    if value.startswith("#"):
        return value.lower()
    return doc["palette"][value].lower()


def resolved_ansi(root=REPO):
    """The 16 resolved [terminal].ansi colours."""
    doc = load_palette_toml(root)
    return [resolve_ref(doc, v) for v in doc["terminal"]["ansi"]]


def resolved_tmux(root=REPO):
    """Every [tmux] role resolved to lowercase hex."""
    doc = load_palette_toml(root)
    return {k: resolve_ref(doc, v) for k, v in doc["tmux"].items()}


def replace_line(path, prefix, new_line):
    """Replace the unique line of a file that starts with prefix."""
    lines = Path(path).read_text().split("\n")
    hits = [i for i, line in enumerate(lines) if line.startswith(prefix)]
    if len(hits) != 1:
        raise AssertionError(f"{prefix!r}: {len(hits)} matching lines")
    lines[hits[0]] = new_line
    Path(path).write_text("\n".join(lines))


def set_ansi(root, entries):
    """Rewrite the [terminal].ansi array of a copy's palette.toml."""
    path = Path(root) / "palette.toml"
    body = ", ".join(f'"{e}"' for e in entries)
    text = re.sub(
        r"(?ms)^ansi\s*=\s*\[.*?\]",
        lambda _m: f"ansi = [{body}]",
        path.read_text(),
    )
    path.write_text(text)


def set_ansi_entry(root, index, value):
    """Change one [terminal].ansi entry of a copy's palette.toml."""
    entries = list(load_palette_toml(root)["terminal"]["ansi"])
    entries[index] = value
    set_ansi(root, entries)


def real_dconf_dump():
    """Read-only dump of the user's real GNOME Terminal settings."""
    return run(["dconf", "dump", "/org/gnome/terminal/"]).stdout


TMUX_ALLOWLIST = frozenset({
    "status-style", "window-status-style", "window-status-current-style",
    "window-status-activity-style", "window-status-bell-style",
    "pane-border-style", "pane-active-border-style", "message-style",
    "message-command-style", "mode-style", "clock-mode-colour",
    "display-panes-colour", "display-panes-active-colour",
    "status-left", "status-right", "window-status-format",
    "window-status-current-format", "window-status-separator",
    "@ukiyo_e_status_date", "@ukiyo_e_status_time",
})
_SERVER_COUNT = [0]


@dataclass(frozen=True)
class TmuxServer:
    """An isolated tmux server on a dedicated -L socket."""

    name: str
    config: Path

    @classmethod
    def start(cls, case):
        """Start a server for a TestCase; kill it on cleanup."""
        _SERVER_COUNT[0] += 1
        name = f"ukiyo_e_test_{os.getpid()}_{_SERVER_COUNT[0]}"
        folder = scratch_dir()
        config = folder / "empty.conf"
        config.write_text("")
        server = cls(name, config)
        case.addCleanup(remove_dir, folder)
        result = server.tmux("new-session", "-d", "-x", "200", "-y", "50")
        if result.code != 0:
            raise AssertionError(f"tmux did not start: {result.stderr}")
        socket = Path(server.tmux("display", "-p", "#{socket_path}")
                      .stdout.strip())
        case.addCleanup(socket.unlink, missing_ok=True)
        case.addCleanup(server.tmux, "kill-server")
        return server

    def tmux(self, *args):
        argv = ["tmux", "-L", self.name, "-f", str(self.config), *args]
        return run(argv, stdin="")

    def value(self, option):
        result = self.tmux("show-options", "-gqv", option)
        return result.stdout.rstrip("\n")

    def run_theme(self, root=REPO):
        """Run ukiyo_e.tmux the way TPM does, against this server."""
        where = self.tmux("display", "-p", "#{socket_path},#{pid}")
        env = dict(os.environ, TMUX=f"{where.stdout.strip()},0")
        return run([str(Path(root) / "ukiyo_e.tmux")], env=env, stdin="")

    def snapshot(self):
        """Global options, window options, and non-option state."""
        return {
            "options": self._options("-g"),
            "window": self._options("-gw"),
            "server": self._options("-s"),
            "keys": self.tmux("list-keys").stdout,
            "hooks": self.tmux("show-hooks", "-g").stdout,
            "environment": self.tmux("show-environment", "-g").stdout,
        }

    def _options(self, scope):
        lines = self.tmux("show-options", scope).stdout.splitlines()
        return dict(line.split(" ", 1) if " " in line else (line, "")
                    for line in lines)


def changed_options(before, after):
    """Option names whose global value differs between snapshots."""
    changed = set()
    for table in ("options", "window", "server"):
        old, new = before[table], after[table]
        changed |= {k for k in set(old) | set(new)
                    if old.get(k) != new.get(k)}
    return changed


GNOME_HARNESS = REPO / "tests" / "gnome_harness.py"


def run_gnome_harness(scenario, root=REPO):
    """Run a harness scenario in a private D-Bus session and dconf db."""
    folder = scratch_dir()
    runtime = folder / "runtime"
    runtime.mkdir(mode=0o700)
    env = dict(os.environ, XDG_CONFIG_HOME=str(folder / "config"),
               XDG_RUNTIME_DIR=str(runtime),
               UKIYO_E_OUTER_BUS=os.environ.get("DBUS_SESSION_BUS_ADDRESS",
                                                ""))
    env.pop("DBUS_SESSION_BUS_ADDRESS", None)
    argv = ["dbus-run-session", "--", sys.executable, str(GNOME_HARNESS),
            scenario, str(root)]
    try:
        result = run(argv, env=env)
    finally:
        remove_dir(folder)
    return result


def parse_dump(text):
    """dconf dump text -> {section: {key: value}}."""
    sections, current = {}, None
    for line in text.splitlines():
        if line.startswith("[") and line.endswith("]"):
            current = sections.setdefault(line[1:-1], {})
        elif "=" in line and current is not None:
            key, value = line.split("=", 1)
            current[key] = value
    return sections


class RealDconfGuard:
    """Fail loudly if the user's real GNOME Terminal settings change."""

    before = None

    @classmethod
    def take(cls):
        cls.before = real_dconf_dump()

    @classmethod
    def verify(cls):
        after = real_dconf_dump()
        if after != cls.before:
            raise AssertionError("REAL DCONF CHANGED")
