"""V-9: the installed ukiyo_e.tmux on a dedicated tmux server."""

import os
import re
import subprocess
import time
import unittest

import support
from configurator import tmux

STYLE_ROLES = {
    "status-style": ("status_fg", "status_bg"),
    "window-status-style": ("window_fg", "window_bg"),
    "window-status-current-style": ("window_current_fg",
                                    "window_current_bg"),
    "window-status-activity-style": ("window_activity_fg",
                                     "window_activity_bg"),
    "window-status-bell-style": ("window_bell_fg", "window_bell_bg"),
    "pane-border-style": ("pane_border_fg", None),
    "pane-active-border-style": ("pane_active_border_fg", None),
    "message-style": ("message_fg", "message_bg"),
    "message-command-style": ("command_fg", "command_bg"),
    "mode-style": ("copy_selection_fg", "copy_selection_bg"),
}
COLOUR_ROLES = {
    "clock-mode-colour": "clock_fg",
    "display-panes-colour": "display_panes_fg",
    "display-panes-active-colour": "display_panes_active_fg",
}
POWERLINE = {chr(c) for c in range(0xE0B0, 0xE0B4)}
THEME_OPTIONS = (tmux.STYLE_OPTIONS + tmux.STATUS_OPTIONS
                 + tmux.PRIVATE_OPTIONS)
FLAT_TEMPLATE = (
    "set -g status-style 'fg={{flat_text_fg}},bg={{flat_bar_bg}}'\n"
    "set -g window-status-style 'fg={{flat_text_fg}},"
    "bg={{flat_bar_bg}}'\n"
    "set -g window-status-current-style 'fg={{flat_current_fg}},"
    "bg={{flat_current_bg}}'\n"
    "set -g status-left '#[fg={{flat_block_fg}},bg={{flat_block_bg}}]"
    " #S #[fg={{flat_separator_fg}},bg={{flat_bar_bg}}]|'\n"
    "set -g status-right '#[fg={{flat_text_fg}},bg={{flat_bar_bg}}]"
    " #{T:@ukiyo_e_status_date} #{T:@ukiyo_e_status_time}"
    " #[fg={{flat_block_fg}},bg={{flat_block_bg}}] #H '\n"
    "set -g window-status-format ' #I.#W '\n"
    "set -g window-status-current-format ' #I.#W '\n"
    "set -g window-status-separator '#[fg={{flat_separator_fg}},"
    "bg={{flat_bar_bg}}]|'\n"
)
FLAT_RENDERED = (
    "# GENERATED by configure.py from palette.toml. Do not edit by hand.\n"
    "set -g status-style 'fg=#7a8382,bg=#282727'\n"
    "set -g window-status-style 'fg=#7a8382,bg=#282727'\n"
    "set -g window-status-current-style 'fg=#c5c9c5,bg=#63322e'\n"
    "set -g status-left '#[fg=#7a8382,bg=#393836] #S "
    "#[fg=#393836,bg=#282727]|'\n"
    "set -g status-right '#[fg=#7a8382,bg=#282727] "
    "#{T:@ukiyo_e_status_date} #{T:@ukiyo_e_status_time} "
    "#[fg=#7a8382,bg=#393836] #H '\n"
    "set -g window-status-format ' #I.#W '\n"
    "set -g window-status-current-format ' #I.#W '\n"
    "set -g window-status-separator '#[fg=#393836,bg=#282727]|'\n"
)
UNCHANGED_SINCE = "e5ddecf"
FLAT_STYLES = {
    "status-style": {"fg": "#7a8382", "bg": "#282727"},
    "window-status-style": {"fg": "#7a8382", "bg": "#282727"},
    "window-status-current-style": {"fg": "#c5c9c5", "bg": "#63322e"},
}


def attribute_map(style):
    """Parse a tmux style string into {attribute: value}."""
    attributes = {}
    for part in style.split(","):
        key, _, value = part.strip().partition("=")
        attributes[key] = value.lower()
    return attributes


def rendered_formats():
    """Option -> value of the 5 format lines of FLAT_RENDERED."""
    found = {}
    for line in FLAT_RENDERED.splitlines()[1:]:
        match = re.fullmatch(r"set -g (\S+) '(.*)'", line)
        found[match.group(1)] = match.group(2)
    return {k: v for k, v in found.items() if k in tmux.STATUS_OPTIONS}


def is_private_use(char):
    code = ord(char)
    return 0xE000 <= code <= 0xF8FF or code >= 0xF0000


class TmuxTestCase(unittest.TestCase):
    def setUp(self):
        self.env = support.scratch_env(self)
        self.server = support.TmuxServer.start(self, self.env)
        self.attached = self.server.attach(self.env)

    def configure(self, *args):
        return support.configure_ok(self.attached, "tmux", *args)

    def run_script(self):
        script = self.env.install / "ukiyo_e.tmux"
        result = self.server.run_script(self.env, script)
        self.assertEqual(result.code, 0, result.stderr)

    def status_values(self):
        return {n: self.server.value(n) for n in tmux.STATUS_OPTIONS}

    def theme_values(self):
        return {n: self.server.value(n) for n in THEME_OPTIONS}


class ConstantsTest(unittest.TestCase):
    def test_allowlist(self):
        self.assertEqual(len(tmux.STYLE_OPTIONS), 13)
        self.assertEqual(len(tmux.STATUS_OPTIONS), 5)
        self.assertEqual(set(THEME_OPTIONS), support.TMUX_ALLOWLIST)


class AllowlistTest(TmuxTestCase):
    def test_install_reloads_allowlisted_options_only(self):
        before = self.server.snapshot()
        result = self.configure()
        self.assertEqual(result.stdout.splitlines()[-1],
                         "  reload tmux server")
        after = self.server.snapshot()
        changed = support.changed_options(before, after)
        self.assertTrue(changed)
        self.assertLessEqual(changed, support.TMUX_ALLOWLIST)
        for key in ("keys", "hooks", "environment"):
            self.assertEqual(before[key], after[key], key)
        self.assertEqual(before["options"]["prefix"],
                         after["options"]["prefix"])

    def test_nothing_set_outside_global_scope(self):
        scopes = (("show-options",), ("show-options", "-w"),
                  ("show-options", "-p"))
        before = [self.server.tmux(*argv).stdout for argv in scopes]
        self.configure()
        after = [self.server.tmux(*argv).stdout for argv in scopes]
        self.assertEqual(after, before)

    def test_styles_match_roles(self):
        self.configure()
        roles = support.resolved_tmux()
        for option, (fg, bg) in STYLE_ROLES.items():
            expected = {"fg": roles[fg]}
            if bg:
                expected["bg"] = roles[bg]
            actual = attribute_map(self.server.value(option))
            self.assertEqual(actual, expected, option)
        for option, role in COLOUR_ROLES.items():
            self.assertEqual(self.server.value(option).lower(),
                             roles[role], option)

    def test_script_idempotent(self):
        self.configure()
        first = self.server.snapshot()
        self.run_script()
        self.run_script()
        self.assertEqual(self.server.snapshot(), first)


class GlyphTest(TmuxTestCase):
    def test_patched_default_has_powerline_glyphs(self):
        self.configure()
        values = self.status_values()
        glyphs = set("".join(values.values())) & POWERLINE
        self.assertTrue(glyphs, values)
        self.assertIn("#{T:@ukiyo_e_status_date}", values["status-right"])

    def test_no_patched_font_has_no_private_use(self):
        self.configure()
        for flag in ("on", "YES", "1", "True"):
            with self.subTest(flag=flag):
                self.server.tmux("set", "-g", "@ukiyo_e_no_patched_font",
                                 flag)
                self.run_script()
                text = "".join(self.status_values().values())
                self.assertIn("#S", text)
                self.assertFalse([c for c in text if is_private_use(c)])


class FlatStaticTest(unittest.TestCase):
    """V-15 (a): the flat template; powerline files unchanged."""

    def test_flat_template(self):
        path = support.REPO / "tmux/status-plain.conf.tmpl"
        self.assertEqual(path.read_bytes(), FLAT_TEMPLATE.encode())

    def test_powerline_files_unchanged(self):
        for rel in ("tmux/status.conf.tmpl", "tmux/colors.conf.tmpl",
                    "tmux/ukiyo_e.tmux"):
            with self.subTest(rel=rel):
                old = subprocess.run(
                    ["git", "-C", str(support.REPO), "show",
                     f"{UNCHANGED_SINCE}:{rel}"],
                    capture_output=True, check=True).stdout
                self.assertEqual((support.REPO / rel).read_bytes(), old)


class FlatLiveTest(TmuxTestCase):
    """V-15 (b)-(g) on a test server after a default install."""

    def setUp(self):
        super().setUp()
        self.defaults = self.theme_values()
        self.configure()
        self.powerline = self.theme_values()

    def flat(self, value="on"):
        self.server.tmux("set", "-g", "@ukiyo_e_no_patched_font", value)
        self.run_script()

    def test_rendered(self):
        path = self.env.install / "tmux/status-plain.conf"
        self.assertEqual(path.read_text(), FLAT_RENDERED)

    def test_flat_on(self):
        before = self.server.snapshot()
        self.flat()
        self.assertEqual(self.status_values(), rendered_formats())
        for option in tmux.STYLE_OPTIONS:
            actual = self.server.value(option)
            if option in FLAT_STYLES:
                self.assertEqual(attribute_map(actual),
                                 FLAT_STYLES[option], option)
            else:
                self.assertEqual(actual, self.powerline[option], option)
        text = "".join(self.status_values().values())
        self.assertFalse([c for c in text if is_private_use(c)])
        for option in ("window-status-format",
                       "window-status-current-format"):
            self.assertIn("#I.#W", self.server.value(option))
            self.assertNotIn("#F", self.server.value(option))
        changed = support.changed_options(before, self.server.snapshot())
        changed.discard("@ukiyo_e_no_patched_font")
        self.assertLessEqual(changed, support.TMUX_ALLOWLIST)
        self.assert_status_right()

    def assert_status_right(self):
        first = time.strftime("%Y-%m-%d %H:%M")
        shown = self.server.tmux("display", "-p", "#{T:status-right}")
        last = time.strftime("%Y-%m-%d %H:%M")
        host = self.server.display("#H")
        blocks = [f"] {stamp} #[fg=#7a8382,bg=#393836] {host} "
                  for stamp in (first, last)]
        self.assertTrue(any(shown.stdout.rstrip("\n").endswith(b)
                            for b in blocks), (shown.stdout, blocks))

    def test_flat_off_restores_powerline(self):
        self.flat()
        self.flat("off")
        self.assertEqual(self.theme_values(), self.powerline)

    def test_status_content_off(self):
        self.flat()
        self.server.tmux("set", "-g", "@ukiyo_e_show_status_content", "off")
        self.server.tmux("set", "-g", "status-left", "mine")
        formats = self.status_values()
        self.flat()
        self.assertEqual(self.status_values(), formats)
        self.assertEqual(self.server.value("status-left"), "mine")
        styles = {o: self.server.value(o) for o in tmux.STYLE_OPTIONS}
        self.assertEqual(styles, {o: self.powerline[o]
                                  for o in tmux.STYLE_OPTIONS})

    def test_flat_idempotent(self):
        self.flat()
        first = self.server.snapshot()
        self.flat()
        self.assertEqual(self.server.snapshot(), first)

    def test_uninstall_after_flat(self):
        self.flat()
        self.configure("--uninstall")
        self.assertEqual(self.theme_values(), self.defaults)


class StatusContentTest(TmuxTestCase):
    def test_status_content_off_keeps_formats(self):
        self.server.tmux("set", "-g", "@ukiyo_e_show_status_content", "OFF")
        before = self.status_values()
        self.configure()
        self.assertEqual(self.status_values(), before)
        roles = support.resolved_tmux()
        expected = {"fg": roles["status_fg"], "bg": roles["status_bg"]}
        self.assertEqual(attribute_map(self.server.value("status-style")),
                         expected)

    def test_date_format_and_twelve_hour_clock(self):
        self.server.tmux("set", "-g", "@ukiyo_e_date_format", "%d/%m")
        self.server.tmux("set", "-gw", "clock-mode-style", "12")
        self.configure()
        first = time.strftime("%I:%M %p")
        shown = self.server.tmux("display", "-p", "#{T:status-right}")
        last = time.strftime("%I:%M %p")
        self.assertIn(time.strftime("%d/%m"), shown.stdout)
        self.assertTrue(first in shown.stdout or last in shown.stdout,
                        shown.stdout)
        self.assertEqual(self.server.value("@ukiyo_e_date_format"), "%d/%m")
        self.assertEqual(self.server.value("@ukiyo_e_status_time"),
                         "%I:%M %p")

    def test_default_date_and_24_hour_clock(self):
        self.configure()
        self.assertEqual(self.server.value("@ukiyo_e_status_date"),
                         "%Y-%m-%d")
        self.assertEqual(self.server.value("@ukiyo_e_status_time"), "%H:%M")
        self.assertEqual(self.server.value("@ukiyo_e_date_format"), "")


class ResetTest(TmuxTestCase):
    def test_uninstall_restores_defaults(self):
        defaults = self.theme_values()
        self.configure()
        self.assertNotEqual(self.theme_values(), defaults)
        result = self.configure("--uninstall")
        self.assertIn("tmux: removed", result.stdout)
        self.assertIn("  reset tmux options", result.stdout)
        self.assertEqual(self.theme_values(), defaults)

    def test_status_content_off_keeps_user_status(self):
        self.server.tmux("set", "-g", "@ukiyo_e_show_status_content", "off")
        self.server.tmux("set", "-g", "status-left", "mine")
        style = self.server.value("status-style")
        self.configure()
        self.configure("--uninstall")
        self.assertEqual(self.server.value("status-left"), "mine")
        self.assertEqual(self.server.value("status-style"), style)


class NoServerTest(unittest.TestCase):
    def test_no_server_running(self):
        env = support.scratch_env(self)
        result = support.configure_ok(env, "tmux")
        self.assertEqual(result.stdout.splitlines()[-1],
                         "  skip tmux reload (no server running)")
        self.assertTrue(env.install.is_symlink())

    def test_tmux_not_found(self):
        env = support.scratch_env(self)
        empty = env.root / "bin"
        empty.mkdir()
        env = env.with_vars(PATH=empty)
        result = support.configure_ok(env, "tmux")
        self.assertEqual(result.stdout.splitlines()[-1],
                         "  skip tmux reload (tmux not found)")


class LocationTest(unittest.TestCase):
    def test_script_reads_its_physical_directory(self):
        env = support.scratch_env(self)
        support.configure_ok(env, "tmux")
        wrapper = env.root / "bin"
        wrapper.mkdir()
        log = env.root / "tmux.log"
        (wrapper / "tmux").write_text(
            f'#!/bin/sh\necho "$*" >> {log}\n')
        (wrapper / "tmux").chmod(0o755)
        path = f"{wrapper}:{os.environ['PATH']}"
        result = support.run([str(env.install / "ukiyo_e.tmux")],
                             env=dict(env.vars, PATH=path), stdin="")
        self.assertEqual(result.code, 0, result.stderr)
        version = env.install.resolve()
        sourced = [line.split(" ", 1)[1] for line in
                   log.read_text().splitlines()
                   if line.startswith("source-file")]
        self.assertEqual(sourced, [f"{version}/tmux/colors.conf",
                                   f"{version}/tmux/status.conf"])


def setUpModule():
    support.RealStateGuard.take()


def tearDownModule():
    support.RealStateGuard.verify()


if __name__ == "__main__":
    unittest.main()
