"""V-11 and V-SAFE: repository layout and Runtime Files checks."""

import ast
import os
import re
import stat
import sys
import unittest

import support
from configurator import gnome, palette, ptyxis, terminal_ansi, tmux
from configurator.settings import KeyChange

RUNTIME_DIRS = ("configurator", "nvim", "tmux")
FORBIDDEN_WORDS = re.compile(r"\b(sudo|curl|wget|git|pip|apt|npm)\b")
NETWORK_MODULES = {"urllib", "http", "socket", "ssl", "ftplib", "smtplib"}
HEX_LITERAL = re.compile(r"(?i)#[0-9a-f]{6}")
EXECUTABLES = {"configure.py", "tmux/ukiyo_e.tmux"}
HEADER = re.compile(r"^(--|#) GENERATED by ")
GSETTINGS_VERBS = {"set", "reset", "reset-recursively"}
# Data Model Slots: slot, name, v1 value, origin, merged list.
SLOT_DATA = (
    ("base00", "lavaBlack", "#181616", "dragonBlack3",
     "dragonBlack0, dragonBlack1, dragonBlack2"),
    ("base01", "cinderBlack", "#2e2d2c", "dragonBlack4", ""),
    ("base02", "basaltGray", "#444343", "dragonBlack5", ""),
    ("base03", "ashGray", "#5a5a59", "dragonBlack6", "sumiInk6"),
    ("base04", "mistGray", "#70706f", "dragonGray3",
     "dragonAsh, katanaGray"),
    ("base05", "hazeGray", "#868785", "dragonGray2", ""),
    ("base06", "cloudGray", "#9c9d9c", "dragonGray", ""),
    ("base07", "snowWhite", "#b2b4b2", "dragonWhite",
     "oldWhite, fujiWhite"),
    ("base08", "fujiRed", "#ae4e47", "dragonRed",
     "samuraiRed, autumnRed, waveRed, winterRed"),
    ("base09", "persimmonOrange", "#9d7257", "dragonOrange",
     "dragonOrange2, roninYellow"),
    ("base0A", "strawYellow", "#ae955e", "dragonYellow",
     "carpYellow, autumnYellow, winterYellow"),
    ("base0B", "pineGreen", "#6e7e60", "dragonGreen2",
     "dragonGreen, autumnGreen, springGreen, winterGreen"),
    ("base0C", "lakeAqua", "#6d8885", "dragonAqua",
     "waveAqua1, waveAqua2"),
    ("base0D", "ridgeBlue", "#668696", "dragonBlue2",
     "dragonBlue, springBlue, waveBlue1, waveBlue2, winterBlue"),
    ("base0E", "twilightViolet", "#68738b", "dragonViolet",
     "dragonTeal, springViolet1"),
    ("base0F", "blossomPink", "#857186", "dragonPink", ""),
)
FORMER_SHADE = re.compile(r"^base0[89A-F]_dark$")
PRIVATE_USE = re.compile("[\ue000-\uf8ff\U000f0000-\U0010fffd]")
LAYOUT_ROLES = {"status_text_fg", "status_segment_bg", "status_block_bg",
                "status_separator_fg", "status_current_fg",
                "status_current_bg"}
REMOVED_TMUX = re.compile(
    r"@ukiyo_e_no_patched_font|status-plain|\bflat_\w+"
    r"|\b(accent_fg|accent_bg|status_segment_fg|window_separator_fg)\b")


def repository_files():
    """Every file of the working tree (no .git, no caches)."""
    found = []
    for top, dirs, names in os.walk(support.REPO):
        dirs[:] = [d for d in dirs if d not in (".git", "__pycache__")]
        for name in names:
            if name != ".git":
                path = os.path.join(top, name)
                found.append(os.path.relpath(path, support.REPO))
    return sorted(found)


def runtime_files():
    """The Runtime Files set of INV-1."""
    return [rel for rel in repository_files()
            if rel == "configure.py" or rel.split("/")[0] in RUNTIME_DIRS]


def text(rel):
    return (support.REPO / rel).read_text()


def imported_modules(rel):
    tree = ast.parse(text(rel))
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            yield from (a.name for a in node.names)
        elif isinstance(node, ast.ImportFrom):
            yield node.module


def constants(node):
    """String constants anywhere below an ast node."""
    return {n.value for n in ast.walk(node)
            if isinstance(n, ast.Constant) and isinstance(n.value, str)}


def uses_settings(rel):
    """settings.py itself or a module importing configurator.settings."""
    for node in ast.walk(ast.parse(text(rel))):
        if not isinstance(node, ast.ImportFrom):
            continue
        names = {a.name for a in node.names}
        if node.module == "configurator.settings" or (
                node.module == "configurator" and "settings" in names):
            return True
    return rel == "configurator/settings.py"


def assigned(tree):
    return {t.id for node in ast.walk(tree) if isinstance(node, ast.Assign)
            for t in node.targets if isinstance(t, ast.Name)}


def slot_line(slot, name, value, origin, merged):
    """The REQ-PAL-6 line of one slot."""
    if slot >= "base08":
        darker = " 20 % darker"
    elif slot == "base07":
        darker = " 10 % darker, saturation -2 points"
    elif slot > "base00":
        darker = f", linear {slot[-1]}/7 from base00 to base07"
    else:
        darker = ""
    tail = f"; merged: {merged}" if merged else ""
    return f'{slot} = "{value}"  # {name}: {origin}{darker}{tail}'


def lua_refs(rel, table):
    """`<table>.<name>` references of one Lua file."""
    return set(re.findall(rf"\b{table}\.(\w+)", text(rel)))


def mapping_values():
    return (set(terminal_ansi.ANSI)
            | set(terminal_ansi.TERMINAL_ROLES.values())
            | set(tmux.TMUX_ROLES.values()))


def template_roles(rel):
    return set(re.findall(r"\{\{(\w+)\}\}", text(rel)))


def sixteen_names(node):
    """A literal list/tuple of 16 string constants."""
    return (isinstance(node, (ast.List, ast.Tuple))
            and len(node.elts) == 16
            and all(isinstance(e, ast.Constant) and isinstance(e.value, str)
                    for e in node.elts))


class RepositoryTest(unittest.TestCase):
    """V-11: INV-8, INV-9, README, runtime self-containment."""

    def test_no_generated_files(self):
        for rel in repository_files():
            first = text(rel).split("\n", 1)[0]
            self.assertIsNone(HEADER.match(first), rel)
        files = repository_files()
        self.assertNotIn("nvim/lua/ukiyo_e/palette.lua", files)
        self.assertNotIn("scripts/generate.py", files)
        self.assertEqual([f for f in files
                          if re.match(r"tmux/.*\.conf$", f)
                          or f.startswith("gnome-terminal/")], [])

    def test_not_a_plugin(self):
        root = os.listdir(support.REPO)
        self.assertNotIn("colors", root)
        self.assertNotIn("lua", root)
        self.assertEqual([n for n in root if n.endswith(".tmux")], [])

    def test_readme_has_no_plugin_install(self):
        readme = text("README.md")
        self.assertNotIn("@plugin", readme)
        self.assertNotIn('"louis01010100/theme"', readme)

    def test_runtime_files_offline(self):
        files = runtime_files()
        self.assertIn("configurator/cli.py", files)
        self.assertIn("nvim/lua/ukiyo_e/init.lua", files)
        for rel in files:
            self.assertNotIn("github.com", text(rel), rel)
            self.assertIsNone(FORBIDDEN_WORDS.search(text(rel)), rel)

    def test_installed_tree_is_self_relative(self):
        env = support.scratch_env(self)
        support.configure_ok(env, "tmux")
        support.configure_ok(env, "nvim")
        for path in env.install.resolve().rglob("*"):
            if path.is_file():
                data = path.read_text()
                for absolute in (str(env.root), str(support.REPO),
                                 os.environ["HOME"]):
                    self.assertNotIn(absolute, data, path)

    def test_palette_toml(self):
        raw = palette.read_toml(support.REPO / "palette.toml")
        self.assertEqual(list(raw), ["palette"])
        self.assertEqual(palette.validate_palette(raw), [])

    def test_no_seed(self):
        """REQ-REPO-6: the kanagawa seed side is gone."""
        words = ("SEED" + "_HASH", "UKIYO_E_KANAGAWA" + "_SEED")
        for rel in repository_files():
            if rel.startswith("tests/") or rel == "README.md":
                for word in words:
                    self.assertNotIn(word, text(rel), rel)


class PaletteTomlTest(unittest.TestCase):
    """V-1 static: the committed palette.toml."""

    def test_slots_and_values(self):
        raw = palette.read_toml(support.REPO / "palette.toml")
        expected = {slot: value for slot, _n, value, _o, _m in SLOT_DATA}
        self.assertEqual(raw["palette"], expected)
        self.assertEqual(tuple(expected), palette.SLOTS)

    def test_slot_comments(self):
        lines = [line for line in text("palette.toml").splitlines()
                 if line.startswith("base")]
        self.assertEqual(lines, [slot_line(*row) for row in SLOT_DATA])

    def test_header_says_shades_not_stored(self):
        header = [line for line in text("palette.toml").splitlines()
                  if line.startswith("[palette]")]
        self.assertEqual(len(header), 1)
        self.assertIn("derived shades are not stored here", header[0])


class SafetyTest(unittest.TestCase):
    """V-SAFE static checks over the Runtime Files."""

    def test_no_hex_literals(self):
        for rel in runtime_files():
            self.assertIsNone(HEX_LITERAL.search(text(rel)), rel)

    def test_stdlib_imports_only(self):
        allowed = sys.stdlib_module_names | {"configurator"}
        for rel in runtime_files():
            if not rel.endswith(".py"):
                continue
            for name in imported_modules(rel):
                top = name.split(".")[0]
                self.assertIn(top, allowed, f"{rel}: {name}")
                self.assertNotIn(top, NETWORK_MODULES, f"{rel}: {name}")

    def test_nvim_names_and_template_roles(self):
        """INV-4."""
        theme = "nvim/lua/ukiyo_e/theme.lua"
        used = lua_refs(theme, "palette")
        shades = lua_refs(theme, "shades")
        self.assertTrue(used and shades)
        self.assertLessEqual(used, set(palette.SLOTS))
        self.assertLessEqual(shades, set(palette.SHADES))
        bare = re.compile(r"""(?<![\w."])(palette|shades)\.\w+""")
        for rel in runtime_files():
            if not rel.endswith(".lua") or rel == theme:
                continue
            if "/highlights/" in rel:
                self.assertNotRegex(text(rel),
                                    r"\b(palette|shades)\.\w+", rel)
            self.assertIsNone(bare.search(text(rel)), rel)
        roles = set()
        for rel in runtime_files():
            if rel.endswith(".tmpl"):
                roles |= template_roles(rel)
        self.assertEqual(roles, set(tmux.TMUX_ROLES))

    def test_mapping_shapes(self):
        """INV-3 (values are checked by test_mapping)."""
        self.assertEqual(len(terminal_ansi.ANSI), 16)
        self.assertEqual(len(tmux.TMUX_ROLES), 27)
        self.assertEqual(len(terminal_ansi.TERMINAL_ROLES), 6)

    def test_two_templates(self):
        """INV-14: exactly the colours and status templates."""
        templates = [r for r in runtime_files() if r.endswith(".tmpl")]
        self.assertEqual(templates, ["tmux/colors.conf.tmpl",
                                     "tmux/status.conf.tmpl"])

    def test_layout_roles_confined(self):
        """INV-14: the 6 layout roles only in the status template."""
        status = template_roles("tmux/status.conf.tmpl")
        self.assertEqual(status, LAYOUT_ROLES | {"status_fg", "status_bg"})
        colours = template_roles("tmux/colors.conf.tmpl")
        self.assertEqual(colours & LAYOUT_ROLES, set())

    def test_no_private_use_in_templates(self):
        """INV-14: no tmux template has a Private Use code point."""
        for rel in runtime_files():
            if rel.endswith(".tmpl"):
                self.assertIsNone(PRIVATE_USE.search(text(rel)), rel)

    def test_no_removed_tmux_names(self):
        """INV-14: no removed option, template, or role is named."""
        for rel in runtime_files():
            self.assertIsNone(REMOVED_TMUX.search(text(rel)), rel)

    def test_no_neutral_accent_or_former_shade_refs(self):
        """INV-14 for mapping values, template roles, and Lua refs."""
        theme = "nvim/lua/ukiyo_e/theme.lua"
        values = (mapping_values() | lua_refs(theme, "palette")
                  | lua_refs(theme, "shades"))
        for rel in runtime_files():
            if rel.endswith(".tmpl"):
                values |= template_roles(rel)
        self.assertFalse(values & set(palette.COLOUR_NAMES), values)
        self.assertEqual([v for v in values if FORMER_SHADE.match(v)],
                         [])

    def test_colour_names_only_in_palette_py(self):
        """INV-14 (stricter: not even in other comments)."""
        words = re.compile(
            r"\b(" + "|".join(palette.COLOUR_NAMES) + r")\b")
        for rel in runtime_files():
            if rel != "configurator/palette.py":
                self.assertIsNone(words.search(text(rel)), rel)

    def test_file_modes(self):
        """REQ-REPO-3 on disk and, when present, in the git index."""
        for rel in repository_files():
            mode = (support.REPO / rel).stat().st_mode
            executable = bool(mode & stat.S_IXUSR)
            self.assertEqual(executable, rel in EXECUTABLES, rel)
        index = support.run(["git", "-C", str(support.REPO), "ls-files",
                             "-s", "--", "configure.py",
                             "tmux/ukiyo_e.tmux"])
        for line in index.stdout.splitlines():
            self.assertTrue(line.startswith("100755 "), line)

    def test_gsettings_writes_confined(self):
        """gsettings run only by settings.py; verbs only in write_args."""
        for rel in runtime_files():
            if not rel.endswith(".py"):
                continue
            tree = ast.parse(text(rel))
            if rel != "configurator/settings.py":
                self.assertNotIn("gsettings", constants(tree), rel)
            if not uses_settings(rel):
                continue
            for func in ast.walk(tree):
                if not isinstance(func, ast.FunctionDef):
                    continue
                verbs = constants(func) & GSETTINGS_VERBS
                if verbs:
                    self.assertEqual((rel, func.name),
                                     ("configurator/settings.py",
                                      "write_args"), verbs)

    def test_gsettings_write_guard(self):
        ok = (KeyChange(gnome.PROFILE, "palette", None, "x", ""),
              KeyChange(gnome.PROFILE, None, None, None, ""),
              KeyChange(gnome.LIST_SCHEMA, "list", None, "x", ""),
              KeyChange(gnome.LIST_SCHEMA, "default", None, "x", ""))
        bad = (KeyChange(gnome.PROFILE, "font", None, "x", ""),
               KeyChange(gnome.LIST_SCHEMA, "other", None, "x", ""),
               KeyChange(gnome.DEFAULTS, "palette", None, "x", ""),
               KeyChange("org.gnome.desktop", "x", None, "x", ""))
        self.assertTrue(all(gnome.allowed(c) for c in ok))
        self.assertFalse(any(gnome.allowed(c) for c in bad))

    def test_ptyxis_write_guard(self):
        """INV-11: label/palette at its path, the two list keys only."""
        other = f"{ptyxis.PROFILE_SCHEMA}:{ptyxis.PROFILES_ROOT}{'1' * 32}/"
        ok = (KeyChange(ptyxis.PROFILE, "label", None, "x", ""),
              KeyChange(ptyxis.PROFILE, "palette", None, "x", ""),
              KeyChange(ptyxis.PROFILE, None, None, None, ""),
              KeyChange(ptyxis.LIST_SCHEMA, "profile-uuids", None, "x",
                        ""),
              KeyChange(ptyxis.LIST_SCHEMA, "default-profile-uuid", None,
                        "x", ""))
        bad = (KeyChange(ptyxis.PROFILE, "opacity", None, "x", ""),
               KeyChange(ptyxis.LIST_SCHEMA, "enable-a11y", None, "x", ""),
               KeyChange(ptyxis.DEFAULTS, "label", None, "x", ""),
               KeyChange(other, "label", None, "x", ""),
               KeyChange(gnome.PROFILE, "palette", None, "x", ""),
               KeyChange("org.gnome.Ptyxis.Shortcuts", "x", None, "x", ""))
        self.assertTrue(all(ptyxis.allowed(c) for c in ok))
        self.assertFalse(any(ptyxis.allowed(c) for c in bad))
        self.assertEqual(ptyxis.write(bad[0], "0.5"),
                         f"refusing to write {ptyxis.PROFILE} opacity")

    def test_ptyxis_uuid(self):
        self.assertRegex(ptyxis.UUID, r"^[0-9a-f]{32}$")
        self.assertNotEqual(ptyxis.UUID, gnome.UUID.replace("-", ""))

    def test_terminal_mappings_defined_once(self):
        """REQ-MAP-2: TERMINAL_ROLES and a 16-name list only once."""
        owners = set()
        for rel in runtime_files():
            if not rel.endswith(".py"):
                continue
            tree = ast.parse(text(rel))
            if "TERMINAL_ROLES" in assigned(tree) or any(
                    sixteen_names(n) for n in ast.walk(tree)):
                owners.add(rel)
        self.assertEqual(owners, {"configurator/terminal_ansi.py"})

    def test_never_runs_ptyxis(self):
        """SAF-4: no `ptyxis` argv and no --import-palette."""
        for rel in runtime_files():
            self.assertNotIn("--import-palette", text(rel), rel)
            if not rel.endswith(".py"):
                continue
            for node in ast.walk(ast.parse(text(rel))):
                if isinstance(node, (ast.List, ast.Tuple)) and node.elts:
                    first = node.elts[0]
                    self.assertFalse(
                        isinstance(first, ast.Constant)
                        and first.value == "ptyxis", f"{rel}:{node.lineno}")

    def test_tmux_never_addresses_a_socket(self):
        """SAF-6: no -L/-S in the configurator."""
        for rel in runtime_files():
            if rel.endswith(".py"):
                self.assertNotRegex(text(rel), r"""["']-[LS]["']""", rel)

    def test_no_pycache(self):
        """Bytecode may exist on disk (.gitignore) but is never tracked."""
        tracked = support.run(["git", "-C", str(support.REPO), "ls-files"])
        self.assertEqual([f for f in tracked.stdout.splitlines()
                          if "__pycache__" in f or f.endswith(".pyc")], [])
        ignore = (support.REPO / ".gitignore").read_text()
        self.assertIn("__pycache__/", ignore.splitlines())


def module_functions(rel):
    tree = ast.parse(text(rel))
    return {node.name: ast.get_source_segment(text(rel), node)
            for node in tree.body if isinstance(node, ast.FunctionDef)}


class GuardUsageTest(unittest.TestCase):
    """SAF-8: modules that run configure.py guard the real state."""

    RUNNERS = ("run_configure(", "configure_ok(", "import gnome_harness",
               "run_installer(")

    def test_every_runner_module_is_guarded(self):
        modules = [rel for rel in repository_files()
                   if rel.startswith("tests/test_")
                   and any(r in text(rel) for r in self.RUNNERS)]
        self.assertIn("tests/test_ptyxis.py", modules)
        for rel in modules:
            functions = module_functions(rel)
            for name, call in (("setUpModule", "RealStateGuard.take()"),
                               ("tearDownModule",
                                "RealStateGuard.verify()")):
                with self.subTest(rel=rel, name=name):
                    self.assertIn(call, functions.get(name, ""))


def setUpModule():
    support.RealStateGuard.take()


def tearDownModule():
    support.RealStateGuard.verify()


if __name__ == "__main__":
    unittest.main()
