"""REQ-INST-6/7: rendered palette module and tmux files."""

import re
import unittest

import support
from configurator import palette, terminal_ansi, tmux
from configurator import nvim

HEADER_LUA = ("-- GENERATED by configure.py from palette.toml."
              " Do not edit by hand.")
HEADER_TMUX = ("# GENERATED by configure.py from palette.toml."
               " Do not edit by hand.")
# Bodies of the v1 committed tmux/*.conf files at 7019839 (header
# line removed), rendered from the v1 palette.
GOLDEN_COLORS = (
    "set -g status-style 'fg=#c8c093,bg=#0d0c0c'\n"
    "set -g window-status-style 'fg=#7a8382,bg=#0d0c0c'\n"
    "set -g window-status-current-style 'fg=#c5c9c5,bg=#3938"
    "36'\n"
    "set -g window-status-activity-style 'fg=#ff9e3b,bg=#0d0"
    "c0c'\n"
    "set -g window-status-bell-style 'fg=#e82424,bg=#0d0c0c'"
    '\n'
    "set -g pane-border-style 'fg=#393836'\n"
    "set -g pane-active-border-style 'fg=#8ba4b0'\n"
    "set -g message-style 'fg=#c8c093,bg=#0d0c0c'\n"
    "set -g message-command-style 'fg=#c5c9c5,bg=#0d0c0c'\n"
    "set -g mode-style 'fg=#c8c093,bg=#2d4f67'\n"
    "set -g clock-mode-colour '#8ba4b0'\n"
    "set -g display-panes-colour '#625e5a'\n"
    "set -g display-panes-active-colour '#ff9e3b'\n"
)
GOLDEN_STATUS = (
    "set -g status-left '#[fg=#0d0c0c,bg=#8ba4b0,bold] #S #["
    "fg=#8ba4b0,bg=#0d0c0c,nobold]\ue0b0'\n"
    "set -g status-right '#[fg=#282727,bg=#0d0c0c]\ue0b2#[fg=#c8c"
    '093,bg=#282727] #{T:@ukiyo_e_status_date} \ue0b3 #{T:@ukiyo_'
    'e_status_time} #[fg=#8ba4b0,bg=#282727]\ue0b2#[fg=#0d0c0c,bg'
    "=#8ba4b0,bold] #H '\n"
    "set -g window-status-format ' #I #W#F '\n"
    "set -g window-status-current-format '#[fg=#0d0c0c,bg=#3"
    "93836]\ue0b0#[default] #I #W#F #[fg=#393836,bg=#0d0c0c]\ue0b0'\n"
    "set -g window-status-separator '#[fg=#625e5a,bg=#0d0c0c"
    "]\ue0b1'\n"
)
GOLDEN_STATUS_PLAIN = (
    "set -g status-left '#[fg=#0d0c0c,bg=#8ba4b0,bold] #S #["
    "fg=#8ba4b0,bg=#0d0c0c,nobold]'\n"
    "set -g status-right '#[fg=#282727,bg=#0d0c0c]#[fg=#c8c0"
    '93,bg=#282727] #{T:@ukiyo_e_status_date} | #{T:@ukiyo_e'
    '_status_time} #[fg=#8ba4b0,bg=#282727]#[fg=#0d0c0c,bg=#'
    "8ba4b0,bold] #H '\n"
    "set -g window-status-format ' #I #W#F '\n"
    "set -g window-status-current-format '#[fg=#0d0c0c,bg=#3"
    "93836]#[default] #I #W#F #[fg=#393836,bg=#0d0c0c]'\n"
    "set -g window-status-separator '#[fg=#625e5a,bg=#0d0c0c"
    "]|'\n"
)


def v1_palette():
    """The v1 [palette] colours (REQUIRED_NAMES only)."""
    raw = palette.read_toml(support.REPO / "palette.toml")
    table = {k: v for k, v in raw["palette"].items()}
    return palette.make_palette({"palette": table})


def rendered_tmux():
    templates = tmux.load_templates(support.REPO)
    return tmux.render(v1_palette(), templates)


def private_use(text):
    return [c for c in text if 0xE000 <= ord(c) <= 0xF8FF]


class PaletteModuleTest(unittest.TestCase):
    def setUp(self):
        self.data = nvim.render_palette_lua(v1_palette())
        self.text = self.data.decode("utf-8")

    def test_header_and_newline(self):
        self.assertEqual(self.text.split("\n")[0], HEADER_LUA)
        self.assertTrue(self.text.endswith("}\n"))
        self.assertNotIn("\r", self.text)

    def test_names_sorted_lowercase(self):
        entries = re.findall(r'^ {8}(\w+) = "(#[0-9a-f]{6})",$',
                             self.text, re.M)
        names = [name for name, _ in entries]
        self.assertEqual(names, sorted(palette.REQUIRED_NAMES))
        self.assertNotRegex(self.text, r"#[0-9a-f]*[A-F]")

    def test_ansi_entries(self):
        body = self.text.split("    ansi = {\n", 1)[1]
        values = re.findall(r'^ {8}"(#[0-9a-f]{6})",$', body, re.M)
        expected = terminal_ansi.resolve_ansi(v1_palette())
        self.assertEqual(tuple(values), expected)
        self.assertNotIn("terminal", self.text)

    def test_deterministic(self):
        again = nvim.render_palette_lua(v1_palette())
        self.assertEqual(again, self.data)


class TmuxRenderTest(unittest.TestCase):
    def setUp(self):
        self.files = rendered_tmux()

    def body(self, rel):
        text = self.files[rel].data.decode("utf-8")
        header, rest = text.split("\n", 1)
        self.assertEqual(header, HEADER_TMUX)
        return rest

    def test_paths_and_modes(self):
        self.assertEqual(sorted(self.files), [
            "tmux/colors.conf", "tmux/status-plain.conf",
            "tmux/status.conf"])
        for spec in self.files.values():
            self.assertEqual(spec.mode, 0o644)

    def test_colors_equal_v1(self):
        self.assertEqual(self.body("tmux/colors.conf"), GOLDEN_COLORS)
        lines = GOLDEN_COLORS.splitlines()
        self.assertEqual(len(lines), 13)

    def test_status_equal_v1(self):
        self.assertEqual(self.body("tmux/status.conf"), GOLDEN_STATUS)
        self.assertTrue(private_use(GOLDEN_STATUS))

    def test_status_plain_equal_v1(self):
        body = self.body("tmux/status-plain.conf")
        self.assertEqual(body, GOLDEN_STATUS_PLAIN)
        self.assertEqual(private_use(body), [])

    def test_deterministic(self):
        self.assertEqual(rendered_tmux(), self.files)

    def test_single_trailing_newline(self):
        for spec in self.files.values():
            self.assertTrue(spec.data.endswith(b"'\n"))
            self.assertNotIn(b"\r", spec.data)


if __name__ == "__main__":
    unittest.main()
