"""REQ-PTX: the Ptyxis palette file and profile (V-13, V-14)."""

import configparser
import hashlib
import os
import unittest
from dataclasses import dataclass

import gnome_harness as harness
import support
from configurator import ptyxis, terminal_ansi
from configurator.palette import InputError

UUID = "9c3e7b1d5a2f4e80b6d4a1c8e7f05b93"
HEADER = ("# GENERATED by configure.py from palette.toml. "
          "Do not edit by hand.")
P, Q = harness.PROFILE_P, harness.PROFILE_Q
OWN = f"Profiles/{UUID}"
INSTALL_LINES = ["ptyxis: updated", "  write palette Ukiyo-e.palette",
                 "  set label", "  set palette", "  list add"]
NO_PTYXIS = "GSettings schema org.gnome.Ptyxis is not installed"
NO_GNOME = ("GSettings schema org.gnome.Terminal.ProfilesList is not "
            "installed")


def expected_palette(root=support.REPO):
    """REQ-PTX-3 bytes, built from the tree's palette.toml."""
    roles = support.resolved_roles(terminal_ansi.TERMINAL_ROLES, root)
    lines = [HEADER, "[Palette]", "Name=Ukiyo-e",
             f"Background={roles['background']}",
             f"Foreground={roles['foreground']}",
             f"Cursor={roles['cursor_bg']}"]
    lines += [f"Color{i}={c}"
              for i, c in enumerate(support.resolved_ansi(root))]
    return ("\n".join(lines) + "\n").encode()


def other_palette():
    """A foreign palette: REQ-PTX-3 shape without the header."""
    return expected_palette().split(b"\n", 1)[1]


def digest(data):
    return hashlib.sha256(data).hexdigest()


def section(dump, name):
    return support.parse_dump(dump).get(name, {})


def ptx_files(env):
    """name -> (mode, SHA-256, mtime) of the regular files in $PTX."""
    folder = support.ptx(env)
    if not folder.is_dir():
        return None
    tree = support.tree_snapshot(folder, skip=())
    return {k: v[2:] for k, v in tree.items() if v[0] == "file"}


@dataclass(frozen=True)
class PtyxisStep:
    """One configure.py run and the state it left."""

    code: int
    stdout: str
    stderr: str
    ptyxis: str
    terminal: str
    files: dict | None

    @property
    def lines(self):
        return self.stdout.splitlines()


def run_step(env, *args, root=support.REPO):
    result = support.run_configure(env, *args, root=root)
    return PtyxisStep(result.code, result.stdout, result.stderr,
                      harness.dump_ptyxis(env.vars),
                      harness.dump(env.vars), ptx_files(env))


def plant_other(env):
    support.ptx(env).mkdir(parents=True, exist_ok=True)
    (support.ptx(env) / "Other.palette").write_bytes(other_palette())


class RenderTest(unittest.TestCase):
    """REQ-PTX-3 content and determinism."""

    def test_bytes(self):
        pal = support.repo_palette()
        data = ptyxis.render_palette(pal)
        self.assertEqual(data, expected_palette())
        self.assertEqual(ptyxis.render_palette(pal), data)

    def test_ini_shape(self):
        parser = configparser.ConfigParser(interpolation=None)
        parser.optionxform = str
        parser.read_string(ptyxis.render_palette(support.repo_palette())
                           .decode())
        self.assertEqual(parser.sections(), ["Palette"])
        keys = list(parser["Palette"])
        self.assertEqual(keys, ["Name", "Background", "Foreground",
                                "Cursor"] + [f"Color{i}"
                                             for i in range(16)])
        self.assertEqual(parser["Palette"]["Name"], "Ukiyo-e")

    def test_one_colour_changes_one_line(self):
        root = support.copy_repo()
        self.addCleanup(support.remove_tree, root)
        support.replace_line(root / "palette.toml", "dragonBlue2 ",
                             'dragonBlue2 = "#123456"')
        old = ptyxis.render_palette(support.repo_palette()).split(b"\n")
        new = ptyxis.render_palette(support.repo_palette(root))
        new = new.split(b"\n")
        differ = [(a, b) for a, b in zip(old, new) if a != b]
        self.assertEqual(len(old), len(new))
        self.assertEqual(differ, [(b"Color4=#8ba4b0", b"Color4=#123456")])


class ParseTest(unittest.TestCase):
    """REQ-PTX-6: strict reading of profile-uuids and the default."""

    GOOD = (("@as []", ()), ("[]", ()), ("['a', 'b']", ("a", "b")),
            ("['b', 'a']", ("b", "a")), ("['']", ("",)),
            (f"['{UUID}']\n", (UUID,)))
    BAD = ("['a','b']", '["a"]', "['a\\'b']", "['a\\\\b']", "garbage",
           "['a', 'b'", "@as ['a']", "['a',  'b']", "")

    def test_accepted(self):
        for text, expected in self.GOOD:
            with self.subTest(text=text):
                self.assertEqual(ptyxis.parse_uuids(text), expected)

    def test_rejected(self):
        for text in self.BAD:
            with self.subTest(text=text):
                with self.assertRaises(InputError) as caught:
                    ptyxis.parse_uuids(text)
                self.assertEqual(
                    str(caught.exception),
                    "ptyxis: cannot parse org.gnome.Ptyxis "
                    f"profile-uuids: {text}")

    def test_default(self):
        self.assertEqual(ptyxis.parse_default("'x'\n"), "x")
        self.assertEqual(ptyxis.parse_default("''"), "")
        with self.assertRaises(InputError) as caught:
            ptyxis.parse_default("x")
        self.assertEqual(str(caught.exception),
                         "ptyxis: cannot parse default-profile-uuid: x")


class OwnershipTest(unittest.TestCase):
    """REQ-PTX-2 (b) on scratch directories (no gsettings)."""

    def setUp(self):
        self.data = support.scratch_dir()
        self.addCleanup(support.remove_dir, self.data)
        self.paths = ptyxis.paths(self.data)

    def refused(self, message):
        with self.assertRaises(InputError) as caught:
            ptyxis.check_owned(self.paths)
        self.assertEqual(str(caught.exception), message)

    def unmanaged(self):
        self.refused(f"{self.paths.file} exists and is not managed by "
                     f"configure.py; move it away and rerun")

    def test_paths(self):
        self.assertEqual(self.paths.root, self.data / "org.gnome.Ptyxis")
        self.assertEqual(self.paths.ptx, self.paths.root / "palettes")
        self.assertEqual(self.paths.file,
                         self.paths.ptx / "Ukiyo-e.palette")

    def test_absent_and_managed(self):
        ptyxis.check_owned(self.paths)
        self.paths.ptx.mkdir(parents=True)
        self.paths.file.write_bytes(expected_palette())
        ptyxis.check_owned(self.paths)

    def test_symlinked_directory(self):
        self.paths.root.mkdir()
        (self.data / "elsewhere").mkdir()
        os.symlink(self.data / "elsewhere", self.paths.ptx)
        ptyxis.check_owned(self.paths)

    def test_not_a_directory(self):
        self.paths.root.write_text("x")
        self.refused(f"{self.paths.root} exists and is not a directory")
        self.paths.root.unlink()
        self.paths.root.mkdir()
        self.paths.ptx.write_text("x")
        self.refused(f"{self.paths.ptx} exists and is not a directory")

    def test_file_without_header(self):
        self.paths.ptx.mkdir(parents=True)
        self.paths.file.write_bytes(expected_palette().split(b"\n", 1)[1])
        self.unmanaged()

    def test_symlink_to_managed_file(self):
        self.paths.ptx.mkdir(parents=True)
        real = self.data / "real.palette"
        real.write_bytes(expected_palette())
        os.symlink(real, self.paths.file)
        self.unmanaged()

    def test_directory_at_file_path(self):
        self.paths.file.mkdir(parents=True)
        self.unmanaged()


class LifecycleTest(unittest.TestCase):
    """V-13 main path with seeds P, Q and Other.palette."""

    STEPS = (("install", ()), ("reinstall", ()),
             ("set_default", ("--set-default",)),
             ("uninstall", ("--uninstall",)),
             ("uninstall_again", ("--uninstall",)))

    @classmethod
    def setUpClass(cls):
        env = support.scratch_env(cls)
        cls.env = harness.start_session(cls, env, {"gnome", "ptyxis"})
        harness.seed_ptyxis(cls.env.vars)
        plant_other(cls.env)
        cls.seeded = harness.dump_ptyxis(cls.env.vars)
        cls.other = ptx_files(cls.env)["Other.palette"]
        cls.steps = {name: run_step(cls.env, "ptyxis", *args)
                     for name, args in cls.STEPS}

    def assert_others_kept(self, step):
        seeded = support.parse_dump(self.seeded)
        for uuid in (P, Q):
            name = f"Profiles/{uuid}"
            self.assertEqual(section(step.ptyxis, name), seeded[name])
        self.assertEqual(step.files["Other.palette"], self.other)
        self.assertEqual(step.terminal, "")

    def test_install(self):
        step = self.steps["install"]
        self.assertEqual(step.code, 0, step.stderr)
        self.assertEqual(step.lines, INSTALL_LINES)
        self.assertEqual(sorted(step.files),
                         ["Other.palette", "Ukiyo-e.palette"])
        self.assertEqual(step.files["Ukiyo-e.palette"][:2],
                         (0o644, digest(expected_palette())))
        self.assertEqual(section(step.ptyxis, OWN),
                         {"label": "'Ukiyo-e'", "palette": "'Ukiyo-e'"})
        self.assertEqual(section(step.ptyxis, "/"), {
            "default-profile-uuid": f"'{P}'",
            "profile-uuids": f"['{P}', '{Q}', '{UUID}']"})
        self.assert_others_kept(step)

    def test_reinstall_changes_nothing(self):
        step = self.steps["reinstall"]
        self.assertEqual(step.code, 0, step.stderr)
        self.assertEqual(step.stdout, "ptyxis: unchanged\n")
        self.assertEqual(step.ptyxis, self.steps["install"].ptyxis)
        self.assertEqual(step.files, self.steps["install"].files)

    def test_set_default(self):
        step = self.steps["set_default"]
        self.assertEqual(step.code, 0, step.stderr)
        self.assertEqual(step.stdout, f"ptyxis: updated\n  default {UUID}\n")
        dump = support.parse_dump(step.ptyxis)
        before = support.parse_dump(self.steps["reinstall"].ptyxis)
        before["/"]["default-profile-uuid"] = f"'{UUID}'"
        self.assertEqual(dump, before)
        self.assertEqual(step.files, self.steps["reinstall"].files)

    def test_uninstall_restores_seeded_state(self):
        step = self.steps["uninstall"]
        self.assertEqual(step.code, 0, step.stderr)
        self.assertEqual(step.lines, [
            "ptyxis: removed", f"  default {P}", "  list remove",
            "  reset profile", "  remove palette Ukiyo-e.palette"])
        self.assertEqual(step.ptyxis, self.seeded)
        self.assertEqual(sorted(step.files), ["Other.palette"])
        self.assert_others_kept(step)

    def test_uninstall_again_is_noop(self):
        step = self.steps["uninstall_again"]
        self.assertEqual(step.code, 0, step.stderr)
        self.assertEqual(step.stdout, "ptyxis: unchanged (not installed)\n")
        self.assertEqual(step.ptyxis, self.seeded)
        self.assertEqual(step.files, self.steps["uninstall"].files)


class EdgeTest(unittest.TestCase):
    """V-13 edges (i)-(v)."""

    def session(self, which=None):
        env = support.scratch_env(self)
        if which is None:
            return harness.start_session(self, env, {"gnome", "ptyxis"})
        return harness.single_schema(self, env, which)

    def test_empty_list(self):
        """(i) install keeps the default ''; uninstall empties dconf."""
        env = self.session()
        step = run_step(env, "ptyxis")
        self.assertEqual(step.lines, INSTALL_LINES, step.stderr)
        self.assertEqual(section(step.ptyxis, "/"),
                         {"profile-uuids": f"['{UUID}']"})
        for folder in (env.data / "org.gnome.Ptyxis", support.ptx(env)):
            self.assertEqual(folder.stat().st_mode & 0o7777, 0o750)
        step = run_step(env, "ptyxis", "--uninstall")
        self.assertEqual(step.lines, [
            "ptyxis: removed", "  list remove", "  reset profile",
            "  remove palette Ukiyo-e.palette"], step.stderr)
        self.assertEqual(step.ptyxis, "")
        self.assertEqual(step.files, {})

    def test_set_default_on_empty_list(self):
        """(ii) both keys are reset by the uninstall."""
        env = self.session()
        step = run_step(env, "ptyxis", "--set-default")
        self.assertEqual(step.lines, INSTALL_LINES + [f"  default {UUID}"])
        step = run_step(env, "ptyxis", "--uninstall")
        self.assertEqual(step.lines, [
            "ptyxis: removed", "  default reset", "  list remove",
            "  reset profile", "  remove palette Ukiyo-e.palette"])
        self.assertEqual(step.ptyxis, "")

    def assert_refused(self, env, message):
        for args in (("ptyxis",), ("ptyxis", "--uninstall"),
                     ("ptyxis", "--dry-run"), ("all",)):
            with self.subTest(args=args):
                before = (support.tree_snapshot(env.root),
                          harness.snapshot_dconf(env.vars))
                result = support.run_configure(env, *args)
                self.assertEqual(result.code, 3, result.stderr)
                self.assertIn(f"configure.py: {message}",
                              result.stderr.splitlines())
                self.assertEqual(result.stdout, "")
                after = (support.tree_snapshot(env.root),
                         harness.snapshot_dconf(env.vars))
                self.assertEqual(support.changed_paths(before[0],
                                                       after[0]), [])
                self.assertEqual(before[1], after[1])

    def test_unmanaged_file(self):
        """(iii) a file without the header, then a symlink."""
        env = self.session()
        target = support.ptx(env) / "Ukiyo-e.palette"
        target.parent.mkdir(parents=True)
        target.write_bytes(other_palette())
        message = (f"{target} exists and is not managed by configure.py; "
                   f"move it away and rerun")
        self.assert_refused(env, message)
        target.unlink()
        (env.root / "real.palette").write_bytes(expected_palette())
        os.symlink(env.root / "real.palette", target)
        self.assert_refused(env, message)

    def test_unparseable_list(self):
        """(iv) an entry with an escaped quote stops every run."""
        env = self.session()
        harness.gsettings(env.vars, "set", harness.PTYXIS,
                          "profile-uuids", "[\"a'b\"]")
        printed = harness.gsettings(env.vars, "get", harness.PTYXIS,
                                    "profile-uuids")
        self.assert_refused(env, "ptyxis: cannot parse org.gnome.Ptyxis "
                            f"profile-uuids: {printed}")

    def test_missing_schema(self):
        """(v) GNOME-only mode: explicit ptyxis exits 3."""
        env = self.session("gnome")
        step = run_step(env, "ptyxis")
        self.assertEqual(step.code, 3, step.stderr)
        self.assertIn(f"configure.py: ptyxis: {NO_PTYXIS}",
                      step.stderr.splitlines())
        self.assertFalse(os.path.lexists(env.data / "org.gnome.Ptyxis"))
        self.assertEqual(harness.dump(env.vars, "/"), "")


class NoTerminalTest(unittest.TestCase):
    """V-8 prerequisites: no gsettings, and no terminal schema."""

    def envs(self):
        plain = harness.start_session(self, support.scratch_env(self))
        empty = plain.root / "empty-bin"
        empty.mkdir()
        none = harness.single_schema(self, support.scratch_env(self),
                                     "none")
        return ((plain.with_vars(PATH=empty),
                 "gsettings not found on PATH",
                 "gsettings not found on PATH"),
                (none, NO_GNOME, NO_PTYXIS))

    def test_named_terminals_fail(self):
        for env, gnome_reason, ptyxis_reason in self.envs():
            for target, why in (("gnome", gnome_reason),
                                ("ptyxis", ptyxis_reason)):
                with self.subTest(target=target, why=why):
                    step = run_step(env, target)
                    self.assertEqual(step.code, 3, step.stderr)
                    self.assertEqual(step.stderr, f"configure.py: "
                                     f"{target}: {why}\n")
                    self.assertIsNone(step.files)
                    self.assertFalse(os.path.lexists(env.install))
                    self.assertEqual(harness.dump(env.vars, "/"), "")

    def test_all_skips_both(self):
        for env, gnome_reason, ptyxis_reason in self.envs():
            with self.subTest(why=ptyxis_reason):
                step = run_step(env, "all")
                self.assertEqual(step.code, 0, step.stderr)
                self.assertEqual(step.lines[:4], [
                    "gnome: skipped (not installed)",
                    f"  {gnome_reason}",
                    "ptyxis: skipped (not installed)",
                    f"  {ptyxis_reason}"])
                self.assertIn("tmux: updated", step.lines)
                self.assertIn("nvim: updated", step.lines)
                self.assertIsNone(step.files)
                self.assertTrue(env.install.is_symlink())
                self.assertEqual(harness.dump(env.vars, "/"), "")


class SingleSchemaTest(unittest.TestCase):
    """V-14 (a)(b)(c) and V-7 case D."""

    def start(self, which):
        env = support.scratch_env(self)
        session = harness.single_schema(self, env, which)
        self.server = support.TmuxServer.start(self, env)
        return self.server.attach(session)

    def snapshots(self, env):
        return (support.tree_snapshot(env.root),
                harness.dump(env.vars, "/"), self.server.snapshot())

    def assert_unchanged(self, env, before):
        after = self.snapshots(env)
        self.assertEqual(support.changed_paths(before[0], after[0]), [])
        self.assertEqual(before[1:], after[1:])

    def test_dry_run_ptyxis_only(self):
        env = self.start("ptyxis")
        before = self.snapshots(env)
        step = run_step(env, "all", "--dry-run")
        self.assertEqual(step.code, 0, step.stderr)
        self.assertEqual(step.lines[:3], [
            "gnome: skipped (not installed)", f"  {NO_GNOME}",
            "ptyxis: would update"])
        self.assertIn("tmux: would update", step.lines)
        self.assert_unchanged(env, before)
        self.assertFalse(os.path.lexists(env.data / "org.gnome.Ptyxis"))

    def test_ptyxis_only(self):
        """(a) and (c)."""
        env = self.start("ptyxis")
        step = run_step(env, "all")
        self.assertEqual(step.code, 0, step.stderr)
        skipped = ["gnome: skipped (not installed)", f"  {NO_GNOME}"]
        self.assertEqual(step.lines[:7], skipped + INSTALL_LINES)
        self.assertEqual([ln for ln in step.lines[7:]
                          if not ln.startswith(" ")],
                         ["tmux: updated", "nvim: updated"])
        self.assertEqual(step.terminal, "")
        before = self.snapshots(env)
        refused = run_step(env, "gnome")
        self.assertEqual(refused.code, 3, refused.stderr)
        self.assert_unchanged(env, before)
        self.assert_set_default(env, skipped)
        step = run_step(env, "all", "--uninstall")
        self.assertEqual(step.code, 0, step.stderr)
        self.assertEqual([ln for ln in step.lines[2:]
                          if not ln.startswith(" ")],
                         ["ptyxis: removed", "tmux: removed",
                          "nvim: removed"])
        self.assertEqual(step.lines[:2], skipped)

    def assert_set_default(self, env, skipped):
        """(c) only default-profile-uuid changes."""
        before = support.parse_dump(harness.dump(env.vars, "/"))
        step = run_step(env, "all", "--set-default")
        self.assertEqual(step.code, 0, step.stderr)
        self.assertEqual(step.lines, skipped + [
            "ptyxis: updated", f"  default {UUID}", "tmux: unchanged",
            "nvim: unchanged"])
        before["org/gnome/Ptyxis"]["default-profile-uuid"] = f"'{UUID}'"
        self.assertEqual(support.parse_dump(harness.dump(env.vars, "/")),
                         before)

    def test_gnome_only(self):
        """(b)."""
        env = self.start("gnome")
        step = run_step(env, "all")
        self.assertEqual(step.code, 0, step.stderr)
        self.assertEqual([ln for ln in step.lines
                          if not ln.startswith(" ")], [
            "gnome: updated", "ptyxis: skipped (not installed)",
            "tmux: updated", "nvim: updated"])
        at = step.lines.index("ptyxis: skipped (not installed)")
        self.assertEqual(step.lines[at + 1], f"  {NO_PTYXIS}")
        self.assertIsNone(step.files)
        self.assertEqual(step.ptyxis, "")
        before = self.snapshots(env)
        refused = run_step(env, "ptyxis")
        self.assertEqual(refused.code, 3, refused.stderr)
        self.assert_unchanged(env, before)
        self.assertFalse(os.path.lexists(env.data / "org.gnome.Ptyxis"))


class HarnessTest(unittest.TestCase):
    """Single-schema sessions and the schema-conditional guard."""

    def session(self, which):
        return harness.single_schema(self, support.scratch_env(self),
                                     which)

    def test_ptyxis_only(self):
        listed = harness.listed_schemas(self.session("ptyxis").vars)
        self.assertLessEqual({"org.gnome.Ptyxis",
                              "org.gnome.Ptyxis.Profile"}, listed)
        self.assertEqual({s for s in listed
                          if not s.startswith("org.gnome.Ptyxis")}, set())

    def test_gnome_only(self):
        listed = harness.listed_schemas(self.session("gnome").vars)
        self.assertLessEqual({"org.gnome.Terminal.ProfilesList",
                              "org.gnome.Terminal.Legacy.Profile"},
                             listed)
        self.assertEqual({s for s in listed
                          if not s.startswith("org.gnome.Terminal")},
                         set())

    def test_no_terminal(self):
        self.assertEqual(harness.listed_schemas(self.session("none").vars),
                         set())

    def test_write_read_round_trip(self):
        env = self.session("ptyxis").vars
        harness.gsettings(env, "set", harness.PTYXIS, "profile-uuids",
                          "['abc']")
        self.assertEqual(harness.gsettings(env, "get", harness.PTYXIS,
                                           "profile-uuids"), "['abc']")
        self.assertEqual(harness.dump_ptyxis(env),
                         "[/]\nprofile-uuids=['abc']\n")
        self.assertEqual(harness.dump(env), "")

    def test_guard_rejects_seeded_state(self):
        session = harness.start_session(self, support.scratch_env(self))
        harness.check_isolation(session.vars, expect={"gnome", "ptyxis"})
        with self.assertRaises(harness.IsolationError):
            harness.check_isolation(session.vars, expect={"ptyxis"})
        harness.gsettings(session.vars, "set", harness.PTYXIS,
                          "default-profile-uuid", "''")
        with self.assertRaises(harness.IsolationError):
            harness.check_isolation(session.vars)
        harness.gsettings(session.vars, "set", harness.PTYXIS,
                          "profile-uuids", f"['{UUID}']")
        with self.assertRaises(harness.IsolationError):
            harness.check_isolation(session.vars)


def setUpModule():
    support.RealStateGuard.take()


def tearDownModule():
    support.RealStateGuard.verify()


if __name__ == "__main__":
    unittest.main()
