"""REQ-INST-6/7: rendered palette module and tmux files."""

import re
import unittest

import support
from configurator import palette, terminal_ansi, tmux
from configurator import nvim

HEADER_LUA = ("-- GENERATED by configure.py from palette.toml."
              " Do not edit by hand.")
HEADER_TMUX = ("# GENERATED by configure.py from palette.toml."
               " Do not edit by hand.")
# Bodies of tmux/colors.conf and tmux/status.conf (header line
# removed), rendered from the committed 16-slot palette.
GOLDEN_COLORS = (
    "set -g status-style 'fg=#c5c9c5,bg=#181616'\n"
    "set -g window-status-style 'fg=#7a8382,bg=#181616'"
    "\n"
    "set -g window-status-current-style 'fg=#c5c9c5,bg="
    "#393836'\n"
    "set -g window-status-activity-style 'fg=#9d7257,bg"
    "=#181616'\n"
    "set -g window-status-bell-style 'fg=#ae4e47,bg=#18"
    "1616'\n"
    "set -g pane-border-style 'fg=#393836'\n"
    "set -g pane-active-border-style 'fg=#668696'\n"
    "set -g message-style 'fg=#c5c9c5,bg=#181616'\n"
    "set -g message-command-style 'fg=#c5c9c5,bg=#18161"
    "6'\n"
    "set -g mode-style 'fg=#c5c9c5,bg=#424f4e'\n"
    "set -g clock-mode-colour '#668696'\n"
    "set -g display-panes-colour '#625e5a'\n"
    "set -g display-panes-active-colour '#9d7257'\n"
)
GOLDEN_STATUS = (
    "set -g status-left '#[fg=#181616,bg=#668696,bold] "
    "#S #[fg=#668696,bg=#181616,nobold]\ue0b0'\n"
    "set -g status-right '#[fg=#282727,bg=#181616]\ue0b2#[fg"
    "=#c5c9c5,bg=#282727] #{T:@ukiyo_e_status_date} \ue0b3 #"
    "{T:@ukiyo_e_status_time} #[fg=#668696,bg=#282727]\ue0b2"
    "#[fg=#181616,bg=#668696,bold] #H '\n"
    "set -g window-status-format ' #I #W#F '\n"
    "set -g window-status-current-format '#[fg=#181616,"
    "bg=#393836]\ue0b0#[default] #I #W#F #[fg=#393836,bg=#18"
    "1616]\ue0b0'\n"
    "set -g window-status-separator '#[fg=#625e5a,bg=#1"
    "81616]\ue0b1'\n"
)


def v1_palette():
    """The committed [palette] colours."""
    raw = palette.read_toml(support.REPO / "palette.toml")
    table = {k: v for k, v in raw["palette"].items()}
    return palette.make_palette({"palette": table})


def rendered_tmux():
    templates = tmux.load_templates(support.REPO)
    return tmux.render(v1_palette(), templates)


def private_use(text):
    return [c for c in text if 0xE000 <= ord(c) <= 0xF8FF]


class PaletteModuleTest(unittest.TestCase):
    def setUp(self):
        self.data = nvim.render_palette_lua(v1_palette())
        self.text = self.data.decode("utf-8")

    def test_header_and_newline(self):
        self.assertEqual(self.text.split("\n")[0], HEADER_LUA)
        self.assertTrue(self.text.endswith("}\n"))
        self.assertNotIn("\r", self.text)

    def block(self, name):
        body = self.text.split(f"    {name} = {{\n", 1)[1]
        return body.split("    },\n", 1)[0]

    def test_names_sorted_lowercase(self):
        entries = re.findall(r'^ {8}(\w+) = "(#[0-9a-f]{6})",$',
                             self.block("palette"), re.M)
        names = [name for name, _ in entries]
        self.assertEqual(names, sorted(palette.SLOTS))
        self.assertNotRegex(self.text, r"#[0-9a-f]*[A-F]")

    def test_palette_module_shades(self):
        expected = "".join(
            f'        {name} = "{value}",\n' for name, value in (
                ("shadowAqua", "#424f4e"), ("shadowBlue", "#3f4e56"),
                ("shadowGreen", "#434a3b"), ("shadowOrange", "#5a4436"),
                ("shadowPink", "#4e444e"), ("shadowRed", "#63322e"),
                ("shadowViolet", "#404450"),
                ("shadowYellow", "#63563a")))
        self.assertEqual(self.block("shades"), expected)
        order = [self.text.index(f"    {k} = {{") for k in
                 ("palette", "shades", "ansi")]
        self.assertEqual(order, sorted(order))

    def test_ansi_entries(self):
        body = self.text.split("    ansi = {\n", 1)[1]
        values = re.findall(r'^ {8}"(#[0-9a-f]{6})",$', body, re.M)
        expected = terminal_ansi.resolve_ansi(v1_palette())
        self.assertEqual(tuple(values), expected)
        self.assertNotIn("terminal", self.text)

    def test_deterministic(self):
        again = nvim.render_palette_lua(v1_palette())
        self.assertEqual(again, self.data)


class TmuxRenderTest(unittest.TestCase):
    def setUp(self):
        self.files = rendered_tmux()

    def body(self, rel):
        text = self.files[rel].data.decode("utf-8")
        header, rest = text.split("\n", 1)
        self.assertEqual(header, HEADER_TMUX)
        return rest

    def test_paths_and_modes(self):
        self.assertEqual(sorted(self.files), [
            "tmux/colors.conf", "tmux/status-plain.conf",
            "tmux/status.conf"])
        for spec in self.files.values():
            self.assertEqual(spec.mode, 0o644)

    def test_colors_equal_v1(self):
        self.assertEqual(self.body("tmux/colors.conf"), GOLDEN_COLORS)
        lines = GOLDEN_COLORS.splitlines()
        self.assertEqual(len(lines), 13)

    def test_status_equal_v1(self):
        self.assertEqual(self.body("tmux/status.conf"), GOLDEN_STATUS)
        self.assertTrue(private_use(GOLDEN_STATUS))

    def test_deterministic(self):
        self.assertEqual(rendered_tmux(), self.files)

    def test_single_trailing_newline(self):
        for spec in self.files.values():
            self.assertTrue(spec.data.endswith(b"'\n"))
            self.assertNotIn(b"\r", spec.data)


if __name__ == "__main__":
    unittest.main()
