"""V-11 and V-SAFE: repository layout and Runtime Files checks."""

import ast
import os
import re
import stat
import sys
import unittest

import support
from configurator import gnome, palette, tmux
from configurator.gnome import KeyChange

RUNTIME_DIRS = ("configurator", "nvim", "tmux")
FORBIDDEN_WORDS = re.compile(r"\b(sudo|curl|wget|git|pip|apt|npm)\b")
NETWORK_MODULES = {"urllib", "http", "socket", "ssl", "ftplib", "smtplib"}
HEX_LITERAL = re.compile(r"(?i)#[0-9a-f]{6}")
EXECUTABLES = {"configure.py", "tmux/ukiyo_e.tmux"}
HEADER = re.compile(r"^(--|#) GENERATED by ")
GSETTINGS_VERBS = {"set", "reset", "reset-recursively"}


def repository_files():
    """Every file of the working tree (no .git, no caches)."""
    found = []
    for top, dirs, names in os.walk(support.REPO):
        dirs[:] = [d for d in dirs if d not in (".git", "__pycache__")]
        for name in names:
            if name != ".git":
                path = os.path.join(top, name)
                found.append(os.path.relpath(path, support.REPO))
    return sorted(found)


def runtime_files():
    """The Runtime Files set of INV-1."""
    return [rel for rel in repository_files()
            if rel == "configure.py" or rel.split("/")[0] in RUNTIME_DIRS]


def text(rel):
    return (support.REPO / rel).read_text()


def imported_modules(rel):
    tree = ast.parse(text(rel))
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            yield from (a.name for a in node.names)
        elif isinstance(node, ast.ImportFrom):
            yield node.module


class RepositoryTest(unittest.TestCase):
    """V-11: INV-8, INV-9, README, runtime self-containment."""

    def test_no_generated_files(self):
        for rel in repository_files():
            first = text(rel).split("\n", 1)[0]
            self.assertIsNone(HEADER.match(first), rel)
        files = repository_files()
        self.assertNotIn("nvim/lua/ukiyo_e/palette.lua", files)
        self.assertNotIn("scripts/generate.py", files)
        self.assertEqual([f for f in files
                          if re.match(r"tmux/.*\.conf$", f)
                          or f.startswith("gnome-terminal/")], [])

    def test_not_a_plugin(self):
        root = os.listdir(support.REPO)
        self.assertNotIn("colors", root)
        self.assertNotIn("lua", root)
        self.assertEqual([n for n in root if n.endswith(".tmux")], [])

    def test_readme_has_no_plugin_install(self):
        readme = text("README.md")
        self.assertNotIn("@plugin", readme)
        self.assertNotIn('"louis01010100/theme"', readme)

    def test_runtime_files_offline(self):
        files = runtime_files()
        self.assertIn("configurator/cli.py", files)
        self.assertIn("nvim/lua/ukiyo_e/init.lua", files)
        for rel in files:
            self.assertNotIn("github.com", text(rel), rel)
            self.assertIsNone(FORBIDDEN_WORDS.search(text(rel)), rel)

    def test_installed_tree_is_self_relative(self):
        env = support.scratch_env(self)
        support.configure_ok(env, "tmux")
        support.configure_ok(env, "nvim")
        for path in env.install.resolve().rglob("*"):
            if path.is_file():
                data = path.read_text()
                for absolute in (str(env.root), str(support.REPO),
                                 os.environ["HOME"]):
                    self.assertNotIn(absolute, data, path)

    def test_palette_toml(self):
        raw = palette.read_toml(support.REPO / "palette.toml")
        self.assertEqual(list(raw), ["palette"])
        self.assertEqual(palette.validate_palette(raw), [])


class SafetyTest(unittest.TestCase):
    """V-SAFE static checks over the Runtime Files."""

    def test_no_hex_literals(self):
        for rel in runtime_files():
            self.assertIsNone(HEX_LITERAL.search(text(rel)), rel)

    def test_stdlib_imports_only(self):
        allowed = sys.stdlib_module_names | {"configurator"}
        for rel in runtime_files():
            if not rel.endswith(".py"):
                continue
            for name in imported_modules(rel):
                top = name.split(".")[0]
                self.assertIn(top, allowed, f"{rel}: {name}")
                self.assertNotIn(top, NETWORK_MODULES, f"{rel}: {name}")

    def test_nvim_names_and_template_roles(self):
        """INV-4."""
        lua = "".join(text(r) for r in runtime_files()
                      if r.endswith(".lua"))
        used = set(re.findall(r"\bpalette\.(\w+)", lua))
        self.assertTrue(used)
        self.assertLessEqual(used, set(palette.REQUIRED_NAMES))
        roles = set()
        for rel in runtime_files():
            if rel.endswith(".tmpl"):
                roles |= set(re.findall(r"\{\{(\w+)\}\}", text(rel)))
        self.assertEqual(roles, set(tmux.TMUX_ROLES))

    def test_mapping_shapes(self):
        """INV-3 (values are checked by test_mapping)."""
        self.assertEqual(len(tmux.TMUX_ROLES), 26)
        self.assertEqual(len(gnome.TERMINAL_ROLES), 6)

    def test_file_modes(self):
        """REQ-REPO-3 on disk and, when present, in the git index."""
        for rel in repository_files():
            mode = (support.REPO / rel).stat().st_mode
            executable = bool(mode & stat.S_IXUSR)
            self.assertEqual(executable, rel in EXECUTABLES, rel)
        index = support.run(["git", "-C", str(support.REPO), "ls-files",
                             "-s", "--", "configure.py",
                             "tmux/ukiyo_e.tmux"])
        for line in index.stdout.splitlines():
            self.assertTrue(line.startswith("100755 "), line)

    def test_gsettings_writes_confined(self):
        """gsettings only in gnome.py; write verbs only in write_args."""
        users = [r for r in runtime_files() if "gsettings" in text(r)]
        self.assertEqual(users, ["configurator/gnome.py"])
        tree = ast.parse(text("configurator/gnome.py"))
        for func in ast.walk(tree):
            if not isinstance(func, ast.FunctionDef):
                continue
            verbs = {n.value for n in ast.walk(func)
                     if isinstance(n, ast.Constant)
                     and n.value in GSETTINGS_VERBS}
            if verbs:
                self.assertEqual(func.name, "write_args", verbs)

    def test_gsettings_write_guard(self):
        ok = (KeyChange(gnome.PROFILE, "palette", None, "x", ""),
              KeyChange(gnome.PROFILE, None, None, None, ""),
              KeyChange(gnome.LIST_SCHEMA, "list", None, "x", ""),
              KeyChange(gnome.LIST_SCHEMA, "default", None, "x", ""))
        bad = (KeyChange(gnome.PROFILE, "font", None, "x", ""),
               KeyChange(gnome.LIST_SCHEMA, "other", None, "x", ""),
               KeyChange(gnome.DEFAULTS, "palette", None, "x", ""),
               KeyChange("org.gnome.desktop", "x", None, "x", ""))
        self.assertTrue(all(gnome.allowed(c) for c in ok))
        self.assertFalse(any(gnome.allowed(c) for c in bad))

    def test_tmux_never_addresses_a_socket(self):
        """SAF-6: no -L/-S in the configurator."""
        for rel in runtime_files():
            if rel.endswith(".py"):
                self.assertNotRegex(text(rel), r"""["']-[LS]["']""", rel)

    def test_no_pycache(self):
        """Bytecode may exist on disk (.gitignore) but is never tracked."""
        tracked = support.run(["git", "-C", str(support.REPO), "ls-files"])
        self.assertEqual([f for f in tracked.stdout.splitlines()
                          if "__pycache__" in f or f.endswith(".pyc")], [])
        ignore = (support.REPO / ".gitignore").read_text()
        self.assertIn("__pycache__/", ignore.splitlines())


if __name__ == "__main__":
    unittest.main()
