"""REQ-INST-6/7: rendered palette module and tmux files."""

import re
import unittest

import support
from configurator import palette, terminal_ansi, tmux
from configurator import nvim

HEADER_LUA = ("-- GENERATED by configure.py from palette.toml."
              " Do not edit by hand.")
HEADER_TMUX = ("# GENERATED by configure.py from palette.toml."
               " Do not edit by hand.")
# Bodies of tmux/colors.conf and tmux/status.conf (header line
# removed), rendered from the committed 16-slot palette.
GOLDEN_COLORS = (
    "set -g status-style 'fg=#b2b4b2,bg=#2e2d2c'\n"
    "set -g window-status-style 'fg=#70706f,bg=#181616'"
    "\n"
    "set -g window-status-current-style 'fg=#b2b4b2,bg="
    "#444343'\n"
    "set -g window-status-activity-style 'fg=#907564,bg"
    "=#181616'\n"
    "set -g window-status-bell-style 'fg=#9c5e59,bg=#18"
    "1616'\n"
    "set -g pane-border-style 'fg=#444343'\n"
    "set -g pane-active-border-style 'fg=#6f838d'\n"
    "set -g message-style 'fg=#b2b4b2,bg=#181616'\n"
    "set -g message-command-style 'fg=#b2b4b2,bg=#18161"
    "6'\n"
    "set -g mode-style 'fg=#b2b4b2,bg=#454c4c'\n"
    "set -g clock-mode-colour '#6f838d'\n"
    "set -g display-panes-colour '#5a5a59'\n"
    "set -g display-panes-active-colour '#907564'\n"
)
GOLDEN_STATUS = (
    "set -g status-style 'fg=#b2b4b2,bg=#2e2d2c'\n"
    'set -g status-left "#[fg=#868785,bg=#444343] #S '
    '#[fg=#444343,bg=#2e2d2c]|"\n'
    'set -g status-right "#[fg=#444343,bg=#2e2d2c]|'
    '#[fg=#868785,bg=#2e2d2c] '
    "#{T:@ukiyo_e_status_date} #[fg=#868785,bg=#2e2d2c]"
    '#{T:@ukiyo_e_status_time} "\n'
    'set -g window-status-format "#[fg=#868785,bg=#2e2d2c] '
    '#I.#W "\n'
    'set -g window-status-current-format "#[fg=#9c9d9c,'
    'bg=#5a3a38] #I.#W "\n'
    'set -g window-status-separator "#[fg=#444343,'
    'bg=#2e2d2c]|"\n'
)


def v1_palette():
    """The committed [palette] colours."""
    raw = palette.read_toml(support.REPO / "palette.toml")
    table = {k: v for k, v in raw["palette"].items()}
    return palette.make_palette({"palette": table})


def rendered_tmux():
    templates = tmux.load_templates(support.REPO)
    return tmux.render(v1_palette(), templates)


def private_use(text):
    return [c for c in text if 0xE000 <= ord(c) <= 0xF8FF]


class PaletteModuleTest(unittest.TestCase):
    def setUp(self):
        self.data = nvim.render_palette_lua(v1_palette())
        self.text = self.data.decode("utf-8")

    def test_header_and_newline(self):
        self.assertEqual(self.text.split("\n")[0], HEADER_LUA)
        self.assertTrue(self.text.endswith("}\n"))
        self.assertNotIn("\r", self.text)

    def block(self, name):
        body = self.text.split(f"    {name} = {{\n", 1)[1]
        return body.split("    },\n", 1)[0]

    def test_names_sorted_lowercase(self):
        entries = re.findall(r'^ {8}(\w+) = "(#[0-9a-f]{6})",$',
                             self.block("palette"), re.M)
        names = [name for name, _ in entries]
        self.assertEqual(names, sorted(palette.SLOTS))
        self.assertNotRegex(self.text, r"#[0-9a-f]*[A-F]")

    def test_palette_module_shades(self):
        expected = "".join(
            f'        {name} = "{value}",\n' for name, value in (
                ("darkAqua", "#454c4c"), ("darkBlue", "#444c52"),
                ("darkGreen", "#43483e"), ("darkOrange", "#54463d"),
                ("darkPink", "#4d464c"), ("darkRed", "#5a3a38"),
                ("darkViolet", "#44464d"),
                ("darkYellow", "#5c5341")))
        self.assertEqual(self.block("shades"), expected)
        order = [self.text.index(f"    {k} = {{") for k in
                 ("palette", "shades", "ansi")]
        self.assertEqual(order, sorted(order))

    def test_ansi_entries(self):
        body = self.text.split("    ansi = {\n", 1)[1]
        values = re.findall(r'^ {8}"(#[0-9a-f]{6})",$', body, re.M)
        expected = terminal_ansi.resolve_ansi(v1_palette())
        self.assertEqual(tuple(values), expected)
        self.assertNotIn("terminal", self.text)

    def test_deterministic(self):
        again = nvim.render_palette_lua(v1_palette())
        self.assertEqual(again, self.data)


class TmuxRenderTest(unittest.TestCase):
    def setUp(self):
        self.files = rendered_tmux()

    def body(self, rel):
        text = self.files[rel].data.decode("utf-8")
        header, rest = text.split("\n", 1)
        self.assertEqual(header, HEADER_TMUX)
        return rest

    def test_paths_and_modes(self):
        self.assertEqual(sorted(self.files), [
            "tmux/colors.conf", "tmux/status.conf"])
        for spec in self.files.values():
            self.assertEqual(spec.mode, 0o644)

    def test_colors_equal_v1(self):
        self.assertEqual(self.body("tmux/colors.conf"), GOLDEN_COLORS)
        lines = GOLDEN_COLORS.splitlines()
        self.assertEqual(len(lines), 13)

    def test_status_equal_v1(self):
        self.assertEqual(self.body("tmux/status.conf"), GOLDEN_STATUS)
        self.assertEqual(private_use(GOLDEN_STATUS), [])

    def test_deterministic(self):
        self.assertEqual(rendered_tmux(), self.files)

    def test_single_trailing_newline(self):
        for spec in self.files.values():
            self.assertTrue(spec.data.endswith(b"\n"))
            self.assertFalse(spec.data.endswith(b"\n\n"))
            self.assertNotIn(b"\r", spec.data)


if __name__ == "__main__":
    unittest.main()
