"""The bash target: roles, rendered prompt script, install."""

import getpass
import os
import shutil
import socket
import unittest

import support
from configurator import bash, palette

HEADER = ("# GENERATED by configure.py from palette.toml."
          " Do not edit by hand.")
# The PS1 line rendered from the committed palette.
GOLDEN_PS1 = (
    r"PS1='\[\e]0;\u@\h: \w\a\]"
    r"\[\e[38;2;90;90;89m\]\u\[\e[38;2;90;90;89m\]@"
    r"\[\e[38;2;90;90;89m\]\h\[\e[38;2;90;90;89m\]:"
    r"\[\e[38;2;112;112;111m\]\w\[\e[38;2;90;90;89m\]\$"
    r"\[\e[0m\] '"
)
# What bash shows for that prompt, as a format of user, host, and path.
EXPANDED = ("\x1b]0;{u}@{h}: {w}\x07"
            "\x1b[38;2;90;90;89m{u}\x1b[38;2;90;90;89m@"
            "\x1b[38;2;90;90;89m{h}\x1b[38;2;90;90;89m:"
            "\x1b[38;2;112;112;111m{w}\x1b[38;2;90;90;89m$"
            "\x1b[0m ")


def committed_palette():
    return palette.make_palette(
        palette.read_toml(support.REPO / "palette.toml"))


class RolesTest(unittest.TestCase):
    def test_committed_roles_valid(self):
        names = palette.colour_names(
            palette.read_toml(support.REPO / "palette.toml"))
        self.assertEqual(bash.validate_roles(names), [])

    def test_unknown_colour_rejected(self):
        roles = dict(bash.BASH_ROLES, path_fg="base99")
        names = palette.colour_names(
            palette.read_toml(support.REPO / "palette.toml"))
        errors = bash.validate_roles(names, roles)
        self.assertEqual(len(errors), 1)
        self.assertIn("BASH_ROLES", str(errors[0]))

    def test_every_role_used(self):
        self.assertEqual([role for role, _ in bash.PARTS],
                         list(bash.ROLE_KEYS))


class RenderTest(unittest.TestCase):
    def test_script(self):
        text = bash.render(committed_palette()).decode()
        self.assertEqual(text, f"{HEADER}\n{GOLDEN_PS1}\n")

    @unittest.skipIf(shutil.which("bash") is None, "bash not found")
    def test_bash_expands_prompt(self):
        folder = support.scratch_dir()
        self.addCleanup(support.remove_dir, folder)
        path = folder / bash.FILENAME
        path.write_bytes(bash.render(committed_palette()))
        script = (f'cd "{folder}"; HOME="{folder.parent}"; '
                  f'source "{path}"; printf %s "${{PS1@P}}"')
        result = support.run(["bash", "--norc", "--noprofile", "-c",
                              script], env={"PATH": os.environ["PATH"]})
        self.assertEqual(result.code, 0, result.stderr)
        self.assertEqual(result.stderr, "")
        expected = EXPANDED.format(u=getpass.getuser(),
                                   h=socket.gethostname().split(".")[0],
                                   w=f"~/{folder.name}")
        self.assertEqual(result.stdout, expected)


class InstallTest(unittest.TestCase):
    def test_install_rerun_uninstall(self):
        env = support.scratch_env(self)
        result = support.configure_ok(env, "bash")
        self.assertEqual(result.stdout.splitlines(), [
            "bash: updated", "  write ukiyo_e.bash",
            "  switch install directory"])
        installed = env.install / bash.FILENAME
        self.assertEqual(installed.read_bytes(),
                         bash.render(committed_palette()))
        self.assertEqual(installed.stat().st_mode & 0o777, 0o644)
        again = support.configure_ok(env, "bash")
        self.assertEqual(again.stdout, "bash: unchanged\n")
        gone = support.configure_ok(env, "bash", "--uninstall")
        self.assertEqual(gone.stdout.splitlines()[0], "bash: removed")
        self.assertFalse(os.path.lexists(env.install))


def setUpModule():
    support.RealStateGuard.take()


def tearDownModule():
    support.RealStateGuard.verify()


if __name__ == "__main__":
    unittest.main()
