"""The dircolors target: roles, rendered database, install."""

import os
import shutil
import unittest

import support
from configurator import dircolors, palette

HEADER = ("# GENERATED by configure.py from palette.toml."
          " Do not edit by hand.")
# LS_COLORS as GNU dircolors prints it for the committed palette.
GOLDEN_LS_COLORS = (
    "rs=0:mh=00:ca=00:mi=00:di=38;2;111;131;141:ln=38;2;114;131;129:"
    "ex=38;2;110;121;101:pi=38;2;144;117;100:so=38;2;130;117;130:"
    "do=38;2;130;117;130:bd=38;2;160;144;108:cd=38;2;160;144;108:"
    "or=38;2;156;94;89:su=38;2;178;180;178;48;2;90;58;56:"
    "sg=38;2;24;22;22;48;2;160;144;108:"
    "st=38;2;178;180;178;48;2;68;76;82:"
    "ow=38;2;178;180;178;48;2;67;72;62:"
    "tw=38;2;24;22;22;48;2;110;121;101:"
)


def committed_palette():
    return palette.make_palette(
        palette.read_toml(support.REPO / "palette.toml"))


class RolesTest(unittest.TestCase):
    def test_committed_roles_valid(self):
        names = palette.colour_names(
            palette.read_toml(support.REPO / "palette.toml"))
        self.assertEqual(dircolors.validate_roles(names), [])

    def test_unknown_colour_rejected(self):
        roles = dict(dircolors.DIRCOLORS_ROLES, dir_fg="base99")
        names = palette.colour_names(
            palette.read_toml(support.REPO / "palette.toml"))
        errors = dircolors.validate_roles(names, roles)
        self.assertEqual(len(errors), 1)
        self.assertIn("DIRCOLORS_ROLES", str(errors[0]))

    def test_every_role_used(self):
        used = {role for _, fg, bg in dircolors.KEYWORDS
                for role in (fg, bg) if role}
        self.assertEqual(used, set(dircolors.ROLE_KEYS))


class RenderTest(unittest.TestCase):
    def test_header_and_types(self):
        lines = dircolors.render(committed_palette()).decode().splitlines()
        self.assertEqual(lines[0], HEADER)
        keywords = [line.split()[0] for line in lines[1:]]
        self.assertEqual(keywords, [p.split()[0] for p in dircolors.PLAIN]
                         + [k for k, _, _ in dircolors.KEYWORDS])

    @unittest.skipIf(shutil.which("dircolors") is None,
                     "dircolors not found")
    def test_dircolors_accepts_database(self):
        folder = support.scratch_dir()
        self.addCleanup(support.remove_dir, folder)
        path = folder / dircolors.FILENAME
        path.write_bytes(dircolors.render(committed_palette()))
        result = support.run(["dircolors", "-b", str(path)],
                             env={"PATH": os.environ["PATH"]})
        self.assertEqual(result.code, 0, result.stderr)
        self.assertEqual(result.stderr, "")
        self.assertIn(f"LS_COLORS='{GOLDEN_LS_COLORS}'", result.stdout)


class InstallTest(unittest.TestCase):
    def test_install_rerun_uninstall(self):
        env = support.scratch_env(self)
        result = support.configure_ok(env, "dircolors")
        self.assertEqual(result.stdout.splitlines(), [
            "dircolors: updated", "  write ukiyo_e.dircolors",
            "  switch install directory"])
        installed = env.install / dircolors.FILENAME
        self.assertEqual(installed.read_bytes(),
                         dircolors.render(committed_palette()))
        self.assertEqual(installed.stat().st_mode & 0o777, 0o644)
        again = support.configure_ok(env, "dircolors")
        self.assertEqual(again.stdout, "dircolors: unchanged\n")
        gone = support.configure_ok(env, "dircolors", "--uninstall")
        self.assertEqual(gone.stdout.splitlines()[0], "dircolors: removed")
        self.assertFalse(os.path.lexists(env.install))


def setUpModule():
    support.RealStateGuard.take()


def tearDownModule():
    support.RealStateGuard.verify()


if __name__ == "__main__":
    unittest.main()
