# GENERATED by scripts/generate.py from palette.toml. Do not edit by hand.
UKIYO_E_BACKGROUND='#181616'
UKIYO_E_FOREGROUND='#c5c9c5'
UKIYO_E_CURSOR_BG='#c8c093'
UKIYO_E_CURSOR_FG='#181616'
UKIYO_E_SELECTION_BG='#2d4f67'
UKIYO_E_SELECTION_FG='#c8c093'
UKIYO_E_PALETTE="['#0d0c0c', '#c4746e', '#8a9a7b', '#c4b28a', '#8ba4b0', '#a292a3', '#8ea4a2', '#c8c093', '#a6a69c', '#e46876', '#87a987', '#e6c384', '#7fb4ca', '#938aa9', '#7aa89f', '#c5c9c5']"
