"""Render palette.toml into the committed Ukiyo-e theme files.

usage: python3 scripts/generate.py [--check]

Write mode rewrites every generated file whose bytes changed and prints
"wrote <path>" for each. Check mode writes nothing and prints
"stale: <path>" for each generated file that differs from palette.toml.
Exit codes: 0 up to date, 1 stale (check mode), 2 usage error,
3 invalid or unreadable input, unsupported Python, or I/O error.
"""

from __future__ import annotations

import os
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = "palette.toml"
USAGE = "usage: generate.py [--check] [-h | --help]"
TABLES = ("palette", "terminal", "tmux")
REQUIRED_PALETTE_NAMES = (
    "autumnGreen", "autumnRed", "autumnYellow", "carpYellow",
    "dragonAqua", "dragonAsh", "dragonBlack0", "dragonBlack1",
    "dragonBlack2", "dragonBlack3", "dragonBlack4", "dragonBlack5",
    "dragonBlack6", "dragonBlue", "dragonBlue2", "dragonGray",
    "dragonGray2", "dragonGray3", "dragonGreen", "dragonGreen2",
    "dragonOrange", "dragonOrange2", "dragonPink", "dragonRed",
    "dragonTeal", "dragonViolet", "dragonWhite", "dragonYellow",
    "fujiWhite", "katanaGray", "oldWhite", "roninYellow", "samuraiRed",
    "springBlue", "springGreen", "springViolet1", "sumiInk6",
    "waveAqua1", "waveAqua2", "waveBlue1", "waveBlue2", "waveRed",
    "winterBlue", "winterGreen", "winterRed", "winterYellow",
)
TERMINAL_SCALARS = (
    "background", "foreground", "cursor_bg", "cursor_fg",
    "selection_bg", "selection_fg",
)
TERMINAL_KEYS = TERMINAL_SCALARS + ("ansi",)
ANSI_COUNT = 16
TMUX_ROLES = (
    "status_fg", "status_bg", "accent_fg", "accent_bg",
    "status_segment_fg", "status_segment_bg", "window_fg", "window_bg",
    "window_current_fg", "window_current_bg", "window_activity_fg",
    "window_activity_bg", "window_bell_fg", "window_bell_bg",
    "window_separator_fg", "pane_border_fg", "pane_active_border_fg",
    "message_fg", "message_bg", "command_fg", "command_bg",
    "copy_selection_fg", "copy_selection_bg", "clock_fg",
    "display_panes_fg", "display_panes_active_fg",
)
PALETTE_LUA = "lua/ukiyo_e/palette.lua"
TMUX_COLORS = "tmux/colors.conf"
TMUX_STATUS = "tmux/status.conf"
TMUX_STATUS_PLAIN = "tmux/status-plain.conf"
PALETTE_SH = "gnome-terminal/palette.sh"
GENERATED_PATHS = (
    PALETTE_LUA, TMUX_COLORS, TMUX_STATUS, TMUX_STATUS_PLAIN, PALETTE_SH,
)
HEADER_TEXT = "GENERATED by scripts/generate.py from palette.toml."
HEADER_LUA = f"-- {HEADER_TEXT} Do not edit by hand."
HEADER_SH = f"# {HEADER_TEXT} Do not edit by hand."
HEX = re.compile(r"^#[0-9A-Fa-f]{6}$")
NAME = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")
# Style options of tmux/colors.conf: option -> (fg role, bg role).
TMUX_STYLES = (
    ("status-style", "status_fg", "status_bg"),
    ("window-status-style", "window_fg", "window_bg"),
    ("window-status-current-style", "window_current_fg",
     "window_current_bg"),
    ("window-status-activity-style", "window_activity_fg",
     "window_activity_bg"),
    ("window-status-bell-style", "window_bell_fg", "window_bell_bg"),
    ("pane-border-style", "pane_border_fg", None),
    ("pane-active-border-style", "pane_active_border_fg", None),
    ("message-style", "message_fg", "message_bg"),
    ("message-command-style", "command_fg", "command_bg"),
    ("mode-style", "copy_selection_fg", "copy_selection_bg"),
)
TMUX_COLOURS = (
    ("clock-mode-colour", "clock_fg"),
    ("display-panes-colour", "display_panes_fg"),
    ("display-panes-active-colour", "display_panes_active_fg"),
)


class UsageError(Exception):
    """The command line is not one the generator accepts."""


class InputError(Exception):
    """Input or I/O failure; carries the stderr lines to print."""

    def __init__(self, lines):
        super().__init__("\n".join(lines))
        self.lines = list(lines)


@dataclass(frozen=True)
class ValidationError:
    """One violated validation rule, addressed as [table].key."""

    table: str
    key: str | None
    reason: str
    index: int | None = None

    def format(self) -> str:
        where = f"[{self.table}]"
        if self.key is not None:
            where += f".{self.key}"
        if self.index is not None:
            where += f"[{self.index}]"
        return f"{SOURCE}: {where}: {self.reason}"

    def sort_key(self):
        known = TABLES.index(self.table) if self.table in TABLES else 3
        index = -1 if self.index is None else self.index
        return (known, self.table, self.key or "", index)


@dataclass(frozen=True)
class ColorRef:
    """A colour value: "#RRGGBB" or the name of a [palette] entry."""

    raw: str

    def resolve(self, palette) -> str:
        value = self.raw if HEX.match(self.raw) else palette[self.raw]
        return value.lower()


@dataclass(frozen=True)
class Palette:
    """Palette names mapped to lowercase hex."""

    colours: dict

    def sorted_items(self):
        return sorted(self.colours.items())


@dataclass(frozen=True)
class TerminalColors:
    """Resolved [terminal] colours."""

    background: str
    foreground: str
    cursor_bg: str
    cursor_fg: str
    selection_bg: str
    selection_fg: str
    ansi: tuple


@dataclass(frozen=True)
class TmuxRoles:
    """Resolved [tmux] roles, keyed by role name."""

    colours: dict

    def __getitem__(self, role: str) -> str:
        return self.colours[role]


@dataclass(frozen=True)
class ResolvedTheme:
    """Every colour of palette.toml, resolved to lowercase hex."""

    palette: Palette
    terminal: TerminalColors
    tmux: TmuxRoles


@dataclass(frozen=True)
class GeneratedFile:
    """The rendered bytes of one generated file."""

    path: str
    content: bytes


@dataclass(frozen=True)
class Glyphs:
    """Status-bar glyphs of one font variant."""

    left: str
    right: str
    divider: str
    separator: str


PATCHED = Glyphs("", "", "", "")
PLAIN = Glyphs("", "", "|", "|")


def parse_args(argv) -> str:
    """Return the run mode: "write", "check", or "help"."""
    if not argv:
        return "write"
    if len(argv) == 1 and argv[0] == "--check":
        return "check"
    if len(argv) == 1 and argv[0] in ("-h", "--help"):
        return "help"
    raise UsageError(" ".join(argv))


def require_python():
    """Refuse to run on a Python without tomllib."""
    if sys.version_info < (3, 11):
        raise InputError(["generate.py: Python 3.11 or later is required"])


def read_toml(path: Path) -> dict:
    """Read and parse palette.toml."""
    import tomllib

    try:
        with open(path, "rb") as handle:
            return tomllib.load(handle)
    except OSError as exc:
        raise InputError([f"{SOURCE}: cannot read: {exc.strerror}"])
    except tomllib.TOMLDecodeError as exc:
        raise InputError([f"{SOURCE}: {exc}"])


def type_name(value) -> str:
    return type(value).__name__


def validate_tables(doc: dict) -> list:
    """V1: exactly the three tables, each a table."""
    errors = []
    for table in TABLES:
        if table not in doc:
            errors.append(ValidationError(table, None,
                                          "missing required table"))
        elif not isinstance(doc[table], dict):
            errors.append(ValidationError(table, None, "expected a table"))
    for table in doc:
        if table not in TABLES:
            errors.append(ValidationError(table, None, "unknown table"))
    return errors


def validate_palette(table: dict) -> list:
    """V2, V3: palette names and hex values."""
    errors = []
    for key, value in table.items():
        if not NAME.match(key):
            errors.append(ValidationError("palette", key, "invalid name"))
        elif not isinstance(value, str):
            reason = f"expected a string, found {type_name(value)}"
            errors.append(ValidationError("palette", key, reason))
        elif not HEX.match(value):
            reason = f'"{value}" is not #RRGGBB'
            errors.append(ValidationError("palette", key, reason))
    for name in REQUIRED_PALETTE_NAMES:
        if name not in table:
            errors.append(ValidationError("palette", name,
                                          "missing required key"))
    return errors


def validate_color(table, key, value, names, index=None) -> list:
    """V7, V8: one colour value is #RRGGBB or a [palette] name."""
    if not isinstance(value, str):
        reason = f"expected a string, found {type_name(value)}"
    elif HEX.match(value) or value in names:
        return []
    else:
        reason = f'"{value}" is neither #RRGGBB nor a [palette] name'
    return [ValidationError(table, key, reason, index)]


def validate_keys(table_name, table, expected) -> list:
    """Missing and unknown keys of a fixed-key table."""
    errors = [ValidationError(table_name, key, "missing required key")
              for key in expected if key not in table]
    errors += [ValidationError(table_name, key, "unknown key")
               for key in table if key not in expected]
    return errors


def validate_ansi(value, names) -> list:
    """V5, V7: the 16-entry ansi array."""
    if not isinstance(value, list):
        reason = f"expected an array, found {type_name(value)}"
        return [ValidationError("terminal", "ansi", reason)]
    errors = []
    if len(value) != ANSI_COUNT:
        reason = f"expected {ANSI_COUNT} entries, found {len(value)}"
        errors.append(ValidationError("terminal", "ansi", reason))
    for index, entry in enumerate(value):
        errors += validate_color("terminal", "ansi", entry, names, index)
    return errors


def validate_terminal(table: dict, names) -> list:
    """V4, V5, V7: the [terminal] table."""
    errors = validate_keys("terminal", table, TERMINAL_KEYS)
    for key in TERMINAL_SCALARS:
        if key in table:
            errors += validate_color("terminal", key, table[key], names)
    if "ansi" in table:
        errors += validate_ansi(table["ansi"], names)
    return errors


def validate_tmux(table: dict, names) -> list:
    """V6, V7: the [tmux] table."""
    errors = validate_keys("tmux", table, TMUX_ROLES)
    for key in TMUX_ROLES:
        if key in table:
            errors += validate_color("tmux", key, table[key], names)
    return errors


def validate(doc: dict) -> list:
    """Every validation error of a parsed palette.toml, sorted."""
    errors = validate_tables(doc)
    tables = {t: doc[t] for t in TABLES if isinstance(doc.get(t), dict)}
    names = set(tables.get("palette", {}))
    if "palette" in tables:
        errors += validate_palette(tables["palette"])
    if "terminal" in tables:
        errors += validate_terminal(tables["terminal"], names)
    if "tmux" in tables:
        errors += validate_tmux(tables["tmux"], names)
    return sorted(errors, key=ValidationError.sort_key)


def resolve(doc: dict) -> ResolvedTheme:
    """Replace palette references by lowercase hex (doc is valid)."""
    source = doc["palette"]
    palette = Palette({k: v.lower() for k, v in source.items()})
    table = doc["terminal"]
    scalars = {k: ColorRef(table[k]).resolve(source)
               for k in TERMINAL_SCALARS}
    ansi = tuple(ColorRef(v).resolve(source) for v in table["ansi"])
    roles = {k: ColorRef(doc["tmux"][k]).resolve(source)
             for k in TMUX_ROLES}
    terminal = TerminalColors(ansi=ansi, **scalars)
    return ResolvedTheme(palette, terminal, TmuxRoles(roles))


def text_file(path: str, lines) -> GeneratedFile:
    """Join lines with LF and one trailing newline."""
    return GeneratedFile(path, ("\n".join(lines) + "\n").encode("utf-8"))


def render_palette_lua(theme: ResolvedTheme) -> GeneratedFile:
    """lua/ukiyo_e/palette.lua: palette and terminal colours."""
    lines = [HEADER_LUA, "return {", "    palette = {"]
    lines += [f'        {name} = "{hex_}",'
              for name, hex_ in theme.palette.sorted_items()]
    lines += ["    },", "    terminal = {"]
    lines += [f'        {key} = "{getattr(theme.terminal, key)}",'
              for key in TERMINAL_SCALARS]
    lines += ["        ansi = {"]
    lines += [f'            "{hex_}",' for hex_ in theme.terminal.ansi]
    lines += ["        },", "    },", "}"]
    return text_file(PALETTE_LUA, lines)


def tmux_set(option: str, value: str) -> str:
    return f"set -g {option} '{value}'"


def render_tmux_colors(theme: ResolvedTheme) -> GeneratedFile:
    """tmux/colors.conf: the 13 style and colour options."""
    roles = theme.tmux
    lines = [HEADER_SH]
    for option, fg, bg in TMUX_STYLES:
        style = f"fg={roles[fg]}" + (f",bg={roles[bg]}" if bg else "")
        lines.append(tmux_set(option, style))
    lines += [tmux_set(option, roles[role])
              for option, role in TMUX_COLOURS]
    return text_file(TMUX_COLORS, lines)


def status_left(roles: TmuxRoles, glyphs: Glyphs) -> str:
    accent = f"fg={roles['accent_fg']},bg={roles['accent_bg']}"
    into_status = f"fg={roles['accent_bg']},bg={roles['status_bg']}"
    return f"#[{accent},bold] #S #[{into_status},nobold]{glyphs.left}"


def status_right(roles: TmuxRoles, glyphs: Glyphs) -> str:
    seg_bg, accent_bg = roles["status_segment_bg"], roles["accent_bg"]
    date = "#{T:@ukiyo_e_status_date}"
    time = "#{T:@ukiyo_e_status_time}"
    return (
        f"#[fg={seg_bg},bg={roles['status_bg']}]{glyphs.right}"
        f"#[fg={roles['status_segment_fg']},bg={seg_bg}]"
        f" {date} {glyphs.divider} {time} "
        f"#[fg={accent_bg},bg={seg_bg}]{glyphs.right}"
        f"#[fg={roles['accent_fg']},bg={accent_bg},bold] #H "
    )


def current_window(roles: TmuxRoles, glyphs: Glyphs) -> str:
    status_bg = roles["status_bg"]
    current_bg = roles["window_current_bg"]
    return (
        f"#[fg={status_bg},bg={current_bg}]{glyphs.left}"
        f"#[default] #I #W#F "
        f"#[fg={current_bg},bg={status_bg}]{glyphs.left}"
    )


def render_tmux_status(theme, path, glyphs) -> GeneratedFile:
    """tmux/status*.conf: the 5 status-content options."""
    roles = theme.tmux
    separator = (f"#[fg={roles['window_separator_fg']},"
                 f"bg={roles['status_bg']}]{glyphs.separator}")
    lines = [
        HEADER_SH,
        tmux_set("status-left", status_left(roles, glyphs)),
        tmux_set("status-right", status_right(roles, glyphs)),
        tmux_set("window-status-format", " #I #W#F "),
        tmux_set("window-status-current-format",
                 current_window(roles, glyphs)),
        tmux_set("window-status-separator", separator),
    ]
    return text_file(path, lines)


def render_palette_sh(theme: ResolvedTheme) -> GeneratedFile:
    """gnome-terminal/palette.sh: bash assignments only."""
    lines = [HEADER_SH]
    lines += [f"UKIYO_E_{key.upper()}='{getattr(theme.terminal, key)}'"
              for key in TERMINAL_SCALARS]
    entries = ", ".join(f"'{hex_}'" for hex_ in theme.terminal.ansi)
    lines.append(f'UKIYO_E_PALETTE="[{entries}]"')
    return text_file(PALETTE_SH, lines)


def render_all(theme: ResolvedTheme) -> tuple:
    """Every generated file, in Generated Files order."""
    return (
        render_palette_lua(theme),
        render_tmux_colors(theme),
        render_tmux_status(theme, TMUX_STATUS, PATCHED),
        render_tmux_status(theme, TMUX_STATUS_PLAIN, PLAIN),
        render_palette_sh(theme),
    )


def on_disk(root: Path, file: GeneratedFile):
    """Current bytes of a generated file, or None when missing."""
    try:
        return (root / file.path).read_bytes()
    except FileNotFoundError:
        return None


def find_stale(root: Path, files) -> list:
    """Paths whose on-disk bytes differ from the rendering."""
    return [f.path for f in files if on_disk(root, f) != f.content]


def write_file(root: Path, file: GeneratedFile):
    """Temp file in the target directory, then rename over the target."""
    target = root / file.path
    target.parent.mkdir(parents=True, exist_ok=True)
    handle, temp = tempfile.mkstemp(dir=target.parent, prefix=".tmp-")
    try:
        with os.fdopen(handle, "wb") as out:
            out.write(file.content)
        os.chmod(temp, 0o644)
        os.replace(temp, target)
    except OSError:
        Path(temp).unlink(missing_ok=True)
        raise


def write_changed(root: Path, files) -> list:
    """Write every stale file; return the written paths."""
    stale = set(find_stale(root, files))
    written = []
    for file in files:
        if file.path not in stale:
            continue
        try:
            write_file(root, file)
        except OSError as exc:
            raise InputError([f"{file.path}: {exc.strerror}"])
        written.append(file.path)
    return written


def load_theme() -> ResolvedTheme:
    """Read, parse, validate, and resolve palette.toml."""
    require_python()
    doc = read_toml(ROOT / SOURCE)
    errors = validate(doc)
    if errors:
        raise InputError([error.format() for error in errors])
    return resolve(doc)


def run_mode(mode: str, files) -> int:
    """Check or write the rendered files; return the exit code."""
    if mode == "check":
        stale = find_stale(ROOT, files)
        for path in stale:
            print(f"stale: {path}")
        return 1 if stale else 0
    for path in write_changed(ROOT, files):
        print(f"wrote {path}")
    return 0


def main(argv) -> int:
    try:
        mode = parse_args(argv)
    except UsageError:
        print(USAGE, file=sys.stderr)
        return 2
    if mode == "help":
        print(USAGE)
        return 0
    try:
        return run_mode(mode, render_all(load_theme()))
    except InputError as exc:
        for line in exc.lines:
            print(line, file=sys.stderr)
        return 3


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
