"""bash: BASH_ROLES and the rendered prompt script."""

from __future__ import annotations

from types import MappingProxyType

from configurator.files import FileSpec
from configurator.palette import Palette, check_role_map, resolve

MODULE = "configurator/bash.py"
BASH_ROLES = MappingProxyType({
    "user_fg": "base03",
    "at_fg": "base03",
    "host_fg": "base03",
    "colon_fg": "base03",
    "path_fg": "base04",
    "prompt_fg": "base03",
})
ROLE_KEYS = tuple(BASH_ROLES)
# Prompt parts in order: (role, bash prompt escape).
PARTS = (
    ("user_fg", r"\u"),
    ("at_fg", "@"),
    ("host_fg", r"\h"),
    ("colon_fg", ":"),
    ("path_fg", r"\w"),
    ("prompt_fg", r"\$"),
)
# The terminal window title, as in Ubuntu's default prompt.
TITLE = r"\[\e]0;\u@\h: \w\a\]"
RESET = r"\[\e[0m\]"
FILENAME = "ukiyo_e.bash"
HEADER = ("# GENERATED by configure.py from palette.toml."
          " Do not edit by hand.")

def validate_roles(names, roles=BASH_ROLES) -> list:
    """REQ-MAP-3 for BASH_ROLES."""
    return check_role_map(MODULE, "BASH_ROLES", roles, ROLE_KEYS, names)

def colour(palette: Palette, role: str) -> str:
    """A non-printing true-colour foreground escape for one role."""
    value = resolve(palette, BASH_ROLES[role])
    red, green, blue = (int(value[i:i + 2], 16) for i in (1, 3, 5))
    return rf"\[\e[38;2;{red};{green};{blue}m\]"

def render(palette: Palette) -> bytes:
    """The prompt script: header and one PS1 assignment."""
    parts = "".join(colour(palette, role) + text for role, text in PARTS)
    ps1 = f"PS1='{TITLE}{parts}{RESET} '"
    return f"{HEADER}\n{ps1}\n".encode("utf-8")

def file_set(palette: Palette) -> dict:
    """The bash subtree: the one rendered prompt script."""
    return {FILENAME: FileSpec(render(palette))}
