"""dircolors: DIRCOLORS_ROLES and the rendered ls colour database."""

from __future__ import annotations

from types import MappingProxyType

from configurator.files import FileSpec
from configurator.palette import Palette, check_role_map, resolve

MODULE = "configurator/dircolors.py"
DIRCOLORS_ROLES = MappingProxyType({
    "dir_fg": "base0D",
    "link_fg": "base0C",
    "exec_fg": "base0B",
    "fifo_fg": "base09",
    "socket_fg": "base0F",
    "device_fg": "base0A",
    "orphan_fg": "base08",
    "setuid_fg": "base07",
    "setuid_bg": "darkRed",
    "setgid_fg": "base00",
    "setgid_bg": "base0A",
    "sticky_fg": "base07",
    "sticky_bg": "darkBlue",
    "other_writable_fg": "base07",
    "other_writable_bg": "darkGreen",
    "sticky_other_writable_fg": "base00",
    "sticky_other_writable_bg": "base0B",
})
ROLE_KEYS = tuple(DIRCOLORS_ROLES)
# dircolors keyword -> (foreground role, background role or None).
KEYWORDS = (
    ("DIR", "dir_fg", None),
    ("LINK", "link_fg", None),
    ("EXEC", "exec_fg", None),
    ("FIFO", "fifo_fg", None),
    ("SOCK", "socket_fg", None),
    ("DOOR", "socket_fg", None),
    ("BLK", "device_fg", None),
    ("CHR", "device_fg", None),
    ("ORPHAN", "orphan_fg", None),
    ("SETUID", "setuid_fg", "setuid_bg"),
    ("SETGID", "setgid_fg", "setgid_bg"),
    ("STICKY", "sticky_fg", "sticky_bg"),
    ("OTHER_WRITABLE", "other_writable_fg", "other_writable_bg"),
    ("STICKY_OTHER_WRITABLE", "sticky_other_writable_fg",
     "sticky_other_writable_bg"),
)
# Keywords left uncoloured, so ls never falls back to its built-ins.
PLAIN = ("RESET 0", "MULTIHARDLINK 00", "CAPABILITY 00", "MISSING 00")
FILENAME = "ukiyo_e.dircolors"
HEADER = ("# GENERATED by configure.py from palette.toml."
          " Do not edit by hand.")

def validate_roles(names, roles=DIRCOLORS_ROLES) -> list:
    """REQ-MAP-3 for DIRCOLORS_ROLES."""
    return check_role_map(MODULE, "DIRCOLORS_ROLES", roles, ROLE_KEYS,
                          names)

def sgr(layer: int, colour: str) -> str:
    """A true-colour SGR parameter: 38 (foreground) or 48 (background)."""
    red, green, blue = (int(colour[i:i + 2], 16) for i in (1, 3, 5))
    return f"{layer};2;{red};{green};{blue}"

def attributes(palette: Palette, fg: str, bg: str | None) -> str:
    codes = [sgr(38, resolve(palette, DIRCOLORS_ROLES[fg]))]
    if bg:
        codes.append(sgr(48, resolve(palette, DIRCOLORS_ROLES[bg])))
    return ";".join(codes)

def render(palette: Palette) -> bytes:
    """The dircolors database: header, plain keywords, coloured types."""
    lines = [HEADER, *PLAIN]
    lines += [f"{keyword} {attributes(palette, fg, bg)}"
              for keyword, fg, bg in KEYWORDS]
    return ("\n".join(lines) + "\n").encode("utf-8")

def file_set(palette: Palette) -> dict:
    """The dircolors subtree: the one rendered database."""
    return {FILENAME: FileSpec(render(palette))}
