"""Neovim: render the palette module and mirror the nvim/ tree."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from configurator.files import FileSpec
from configurator.palette import InputError, Palette, ValidationError
from configurator.terminal_ansi import resolve_ansi

HEADER = ("-- GENERATED by configure.py from palette.toml."
          " Do not edit by hand.")
PALETTE_MODULE = "lua/ukiyo_e/palette.lua"
SOURCE_DIR = "nvim"
RESERVED = ("reserved path (rendered by configure.py); remove it from "
            "the source tree")
SYMLINK = "symlink in the source tree (only regular files are installed)"


def render_palette_lua(palette: Palette) -> bytes:
    """lua/ukiyo_e/palette.lua: every palette entry plus `ansi`."""
    lines = [HEADER, "return {", "    palette = {"]
    lines += [f'        {name} = "{value}",'
              for name, value in sorted(palette.colors.items())]
    lines += ["    },", "    ansi = {"]
    lines += [f'        "{value}",' for value in resolve_ansi(palette)]
    lines += ["    },", "}"]
    return ("\n".join(lines) + "\n").encode("utf-8")


@dataclass(frozen=True)
class SourceEntry:
    """One non-directory entry under nvim/ and its install relpath."""

    rel: str
    path: Path


def source_entries(repo: Path) -> list:
    """Every non-directory entry under nvim/, sorted by relpath."""
    root = repo / SOURCE_DIR
    found = []
    for top, dirs, names in os.walk(root):
        for name in dirs + names:
            path = Path(top) / name
            if path.is_symlink() or not path.is_dir():
                rel = path.relative_to(root).as_posix()
                found.append(SourceEntry(rel, path))
    return sorted(found, key=lambda entry: entry.rel)


def validate_sources(repo: Path) -> list:
    """LD-6: no symlink and no reserved palette module under nvim/."""
    errors = []
    for entry in source_entries(repo):
        address = f"{SOURCE_DIR}/{entry.rel}"
        if entry.path.is_symlink():
            errors.append(ValidationError(address, SYMLINK))
        elif entry.rel == PALETTE_MODULE:
            errors.append(ValidationError(address, RESERVED))
    return errors


def read_source(path: Path) -> bytes:
    try:
        return path.read_bytes()
    except OSError as exc:
        raise InputError(f"{path}: cannot read: {exc.strerror}")


def file_set(repo: Path, palette: Palette) -> dict:
    """The nvim subtree: copies of nvim/ plus the palette module."""
    tree = {entry.rel: FileSpec(read_source(entry.path))
            for entry in source_entries(repo)}
    tree[PALETTE_MODULE] = FileSpec(render_palette_lua(palette))
    return tree
