"""Ptyxis: the "Ukiyo-e" palette file and profile."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Mapping

from configurator import files, settings
from configurator.files import FileSpec, unmanaged
from configurator.palette import (InputError, Palette, ValidationError,
                                  map_addr, resolve)
from configurator.settings import DesiredKey, KeyChange, format_as, quote
from configurator.terminal_ansi import TERMINAL_ROLES, resolve_ansi

MODULE = "configurator/ptyxis.py"
PTYXIS_KEYS = MappingProxyType({
    "Background": "background",
    "Foreground": "foreground",
    "Cursor": "cursor_bg",
})
KEY_ORDER = ("Background", "Foreground", "Cursor")
PREFIX = "ptyxis"
HEADER = ("# GENERATED by configure.py from palette.toml."
          " Do not edit by hand.")
NAME = "Ukiyo-e"
FILE_NAME = f"{NAME}.palette"
TEMP_PREFIX = f".{FILE_NAME}.new-"
FILE_MODE = 0o644
DIR_MODE = 0o750
UUID = "9c3e7b1d5a2f4e80b6d4a1c8e7f05b93"
LIST_SCHEMA = "org.gnome.Ptyxis"
PROFILE_SCHEMA = "org.gnome.Ptyxis.Profile"
PROFILES_ROOT = "/org/gnome/Ptyxis/Profiles/"
PROFILE = f"{PROFILE_SCHEMA}:{PROFILES_ROOT}{UUID}/"
# Read only: an unused profile path reports the schema defaults.
DEFAULTS = f"{PROFILE_SCHEMA}:{PROFILES_ROOT}{'0' * 32}/"
PROFILE_KEYS = ("label", "palette")
LIST_KEYS = ("profile-uuids", "default-profile-uuid")
LIST_RE = re.compile(r"\[('[^'\\]*'(?:, '[^'\\]*')*)?\]")
STRING_RE = re.compile(r"'([^'\\]*)'")


@dataclass(frozen=True)
class PaletteFile:
    """The bytes and permission bits of Ukiyo-e.palette."""

    data: bytes
    mode: int = FILE_MODE


@dataclass(frozen=True)
class PtyxisPaths:
    """$DATA/org.gnome.Ptyxis, $PTX and $PTX/Ukiyo-e.palette."""

    root: Path
    ptx: Path
    file: Path


@dataclass(frozen=True)
class PtyxisDesired:
    """The rendered palette file and the two profile keys."""

    file: PaletteFile
    keys: tuple


@dataclass(frozen=True)
class PtyxisState:
    """Read-only probe: profile keys, defaults, list, default, file."""

    values: Mapping
    defaults: Mapping
    uuids: tuple
    default: str
    file: PaletteFile | None


@dataclass(frozen=True)
class PaletteChange:
    """Write (new) or remove (new None) Ukiyo-e.palette; old: rollback."""

    old: PaletteFile | None
    new: PaletteFile | None
    detail: str


@dataclass(frozen=True)
class ProfileReset:
    """reset-recursively of the profile path.

    restore: the recorded non-default label/palette values, the only
    keys a rollback rewrites (INV-11), so a rollback cannot bring back
    other keys of the profile (e.g. a user's opacity): best effort.
    """

    restore: tuple
    detail: str = "reset profile"


@dataclass(frozen=True)
class PtyxisPlan:
    """The ordered file and key changes of the ptyxis step."""

    changes: tuple
    installed: bool = True

    @property
    def details(self) -> tuple:
        return tuple(change.detail for change in self.changes)


def validate_keys(keys=PTYXIS_KEYS) -> list:
    """REQ-MAP-3: exactly three keys, each a TERMINAL_ROLES role."""
    errors = []
    for key in KEY_ORDER:
        if key not in keys:
            errors.append(ValidationError(
                map_addr(MODULE, "PTYXIS_KEYS", key), "missing role"))
    for key, role in keys.items():
        address = map_addr(MODULE, "PTYXIS_KEYS", key)
        if key not in KEY_ORDER:
            errors.append(ValidationError(address, "unknown role"))
        elif role not in TERMINAL_ROLES:
            errors.append(ValidationError(
                address, f'"{role}" is not a TERMINAL_ROLES role'))
    return errors


def render_palette(palette: Palette) -> bytes:
    """REQ-PTX-3: header, [Palette], Name, 3 keys, Color0..15."""
    lines = [HEADER, "[Palette]", f"Name={NAME}"]
    for key in KEY_ORDER:
        role = TERMINAL_ROLES[PTYXIS_KEYS[key]]
        lines.append(f"{key}={resolve(palette, role)}")
    for index, colour in enumerate(resolve_ansi(palette)):
        lines.append(f"Color{index}={colour}")
    return ("\n".join(lines) + "\n").encode()


def parse_uuids(text: str) -> tuple:
    """REQ-PTX-6: the printed profile-uuids, kept verbatim."""
    value = text.rstrip("\n")
    if value == "@as []":
        return ()
    if not LIST_RE.fullmatch(value):
        raise InputError(f"{PREFIX}: cannot parse {LIST_SCHEMA} "
                         f"profile-uuids: {value}")
    return tuple(STRING_RE.findall(value))


def parse_default(text: str) -> str:
    """default-profile-uuid as a single-quoted string."""
    value = text.rstrip("\n")
    match = STRING_RE.fullmatch(value)
    if not match:
        raise InputError(f"{PREFIX}: cannot parse default-profile-uuid: "
                         f"{value}")
    return match.group(1)


def paths(data: Path) -> PtyxisPaths:
    root = data / "org.gnome.Ptyxis"
    return PtyxisPaths(root, root / "palettes",
                       root / "palettes" / FILE_NAME)


def is_managed(path: Path) -> bool:
    """A regular file (not a symlink) whose first line is HEADER."""
    if path.is_symlink() or not path.is_file():
        return False
    try:
        with open(path, "rb") as handle:
            first = handle.readline(len(HEADER) + 2)
    except OSError:
        return False
    return first.rstrip(b"\n") == HEADER.encode()


def check_owned(where: PtyxisPaths) -> None:
    """REQ-PTX-2 (b): directories, and a managed Ukiyo-e.palette."""
    for folder in (where.root, where.ptx):
        if os.path.lexists(folder) and not folder.is_dir():
            raise InputError(f"{folder} exists and is not a directory")
    if os.path.lexists(where.file) and not is_managed(where.file):
        raise unmanaged(where.file)


def missing() -> str | None:
    """REQ-PTX-2 (a): gsettings and both Ptyxis schemas."""
    return settings.missing(LIST_SCHEMA, PROFILE_SCHEMA)


def desired(palette: Palette) -> PtyxisDesired:
    """REQ-PTX-3 and REQ-PTX-5 values."""
    keys = tuple(DesiredKey(key, quote(NAME)) for key in PROFILE_KEYS)
    return PtyxisDesired(PaletteFile(render_palette(palette)), keys)


def read_file(path: Path) -> PaletteFile | None:
    """The current (managed) palette file's bytes and mode."""
    if not os.path.lexists(path):
        return None
    return PaletteFile(path.read_bytes(), path.stat().st_mode & 0o7777)


def probe(where: PtyxisPaths) -> PtyxisState:
    """Current keys, defaults, profile-uuids, default, and file."""
    uuids = parse_uuids(read("get", LIST_SCHEMA, "profile-uuids"))
    default = parse_default(read("get", LIST_SCHEMA,
                                 "default-profile-uuid"))
    return PtyxisState(read_profile(PROFILE), read_profile(DEFAULTS),
                       uuids, default, read_file(where.file))


def read(*args) -> str:
    return settings.read(PREFIX, *args)


def read_profile(schema_path: str) -> dict:
    return settings.read_profile(PREFIX, schema_path)


def key_change(wanted: DesiredKey, state: PtyxisState) -> KeyChange:
    current = state.values.get(wanted.key)
    unset = current == state.defaults.get(wanted.key)
    return KeyChange(PROFILE, wanted.key, None if unset else current,
                     wanted.value, f"set {wanted.key}")


def plan_install(want: PtyxisDesired, state: PtyxisState,
                 set_default: bool) -> PtyxisPlan:
    """REQ-PTX-5/8: file, keys, registration, then default."""
    changes = []
    if state.file != want.file:
        changes.append(PaletteChange(state.file, want.file,
                                     f"write palette {FILE_NAME}"))
    changes += [key_change(k, state) for k in want.keys
                if state.values.get(k.key) != k.value]
    if UUID not in state.uuids:
        changes.append(KeyChange(LIST_SCHEMA, "profile-uuids",
                                 format_as(state.uuids),
                                 format_as(state.uuids + (UUID,)),
                                 "list add"))
    if set_default and state.default != UUID:
        changes.append(KeyChange(LIST_SCHEMA, "default-profile-uuid",
                                 quote(state.default), quote(UUID),
                                 f"default {UUID}"))
    return PtyxisPlan(tuple(changes))


def default_change(state: PtyxisState, remaining) -> list:
    """REQ-PTX-9 step 1."""
    if state.default != UUID:
        return []
    old = quote(state.default)
    if not remaining:
        return [KeyChange(LIST_SCHEMA, "default-profile-uuid", old, None,
                          "default reset")]
    return [KeyChange(LIST_SCHEMA, "default-profile-uuid", old,
                      quote(remaining[0]), f"default {remaining[0]}")]


def list_change(state: PtyxisState, remaining) -> list:
    """REQ-PTX-9 step 2: without the UUID, or the schema default."""
    if UUID not in state.uuids:
        return []
    new = format_as(remaining) if remaining else None
    return [KeyChange(LIST_SCHEMA, "profile-uuids",
                      format_as(state.uuids), new, "list remove")]


def reset_change(state: PtyxisState) -> list:
    """REQ-PTX-9 step 3, recording label/palette for the rollback."""
    differs = [k for k, v in state.values.items()
               if v != state.defaults.get(k)]
    if UUID not in state.uuids and not differs:
        return []
    restore = tuple(KeyChange(PROFILE, k, None, state.values[k], "")
                    for k in PROFILE_KEYS if k in differs)
    return [ProfileReset(restore)]


def plan_uninstall(state: PtyxisState) -> PtyxisPlan:
    """REQ-PTX-9; `unchanged (not installed)` when not installed."""
    if UUID not in state.uuids and state.file is None:
        return PtyxisPlan((), installed=False)
    remaining = tuple(u for u in state.uuids if u != UUID)
    changes = (default_change(state, remaining)
               + list_change(state, remaining) + reset_change(state))
    if state.file is not None:
        changes.append(PaletteChange(state.file, None,
                                     f"remove palette {FILE_NAME}"))
    return PtyxisPlan(tuple(changes))


def gc_leftovers(where: PtyxisPaths) -> tuple:
    """REQ-PTX-4: delete $PTX/.Ukiyo-e.palette.new-* (warnings)."""
    warnings = ()
    if not where.ptx.is_dir():
        return warnings
    for path in sorted(where.ptx.glob(TEMP_PREFIX + "*")):
        warnings += files.remove_path(path)
    return warnings


def allowed(change: KeyChange) -> bool:
    """INV-11: label/palette at the profile path, the two list keys."""
    if change.schema == PROFILE:
        return change.key is None or change.key in PROFILE_KEYS
    return change.schema == LIST_SCHEMA and change.key in LIST_KEYS


def write(change: KeyChange, value: str | None) -> str | None:
    return settings.write(change, value, allowed)


def make_dirs(where: PtyxisPaths) -> None:
    """Create missing $DATA/org.gnome.Ptyxis and $PTX with 0750."""
    for folder in (where.root, where.ptx):
        if not folder.is_dir():
            os.mkdir(folder, DIR_MODE)
            os.chmod(folder, DIR_MODE)


def put_file(where: PtyxisPaths, wanted: PaletteFile) -> None:
    """REQ-PTX-4: temp file, flush, rename over, flush $PTX."""
    make_dirs(where)
    temp = where.ptx / f"{TEMP_PREFIX}{os.getpid()}"
    try:
        files.write_one(temp, FileSpec(wanted.data, wanted.mode))
        os.replace(temp, where.file)
    except BaseException:
        files.remove_path(temp)
        raise
    files.fsync_dir(where.ptx)


def drop_file(where: PtyxisPaths) -> None:
    """REQ-PTX-9 step 4: one unlink, then flush $PTX."""
    where.file.unlink(missing_ok=True)
    files.fsync_dir(where.ptx)


def set_file(where: PtyxisPaths, wanted: PaletteFile | None) -> None:
    if wanted is None:
        drop_file(where)
    else:
        put_file(where, wanted)


def do(change, where: PtyxisPaths) -> str | None:
    """Apply one change; a failure reason or None."""
    try:
        if isinstance(change, PaletteChange):
            set_file(where, change.new)
            return None
        if isinstance(change, ProfileReset):
            return write(KeyChange(PROFILE, None, None, None, ""), None)
        return write(change, change.new)
    except OSError as exc:
        return files.reason(exc)


def undo(change, where: PtyxisPaths) -> None:
    """REQ-PTX-10: restore one recorded value or file (best effort)."""
    try:
        if isinstance(change, PaletteChange):
            set_file(where, change.old)
        elif isinstance(change, ProfileReset):
            for key in change.restore:
                write(key, key.new)
        else:
            write(change, change.old)
    except OSError:
        pass


def apply(plan: PtyxisPlan, where: PtyxisPaths) -> str | None:
    """Apply in order; on failure or signal roll back, return why."""
    return settings.apply(plan.changes, lambda c: do(c, where),
                          lambda c: undo(c, where))
