"""tmux: TMUX_ROLES, templates, rendering, reload and reset."""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass
from types import MappingProxyType

from configurator.files import EXEC_MODE, FileSpec
from configurator.palette import (InputError, Palette, ValidationError,
                                  check_role_map, resolve, tmpl_addr)

MODULE = "configurator/tmux.py"
TMUX_ROLES = MappingProxyType({
    "status_fg": "base07",
    "status_bg": "base01",
    "window_fg": "base04",
    "window_bg": "base00",
    "window_current_fg": "base07",
    "window_current_bg": "base02",
    "window_activity_fg": "base09",
    "window_activity_bg": "base00",
    "window_bell_fg": "base08",
    "window_bell_bg": "base00",
    "pane_border_fg": "base02",
    "pane_active_border_fg": "base0D",
    "message_fg": "base07",
    "message_bg": "base00",
    "command_fg": "base07",
    "command_bg": "base00",
    "copy_selection_fg": "base07",
    "copy_selection_bg": "darkAqua",
    "clock_fg": "base0D",
    "display_panes_fg": "base03",
    "display_panes_active_fg": "base09",
    "status_text_fg": "base05",
    "status_segment_bg": "base01",
    "status_block_bg": "base02",
    "status_separator_fg": "base02",
    "status_current_fg": "base06",
    "status_current_bg": "darkRed",
})
ROLE_KEYS = tuple(TMUX_ROLES)
STYLE_OPTIONS = (
    "status-style", "window-status-style", "window-status-current-style",
    "window-status-activity-style", "window-status-bell-style",
    "pane-border-style", "pane-active-border-style", "message-style",
    "message-command-style", "mode-style", "clock-mode-colour",
    "display-panes-colour", "display-panes-active-colour",
)
STATUS_OPTIONS = (
    "status-left", "status-right", "window-status-format",
    "window-status-current-format", "window-status-separator",
)
PRIVATE_OPTIONS = ("@ukiyo_e_status_date", "@ukiyo_e_status_time")
PLACEHOLDER = re.compile(r"\{\{([^{}]*)\}\}")
HEX_LITERAL = re.compile(r"#[0-9A-Fa-f]{6}")
SCRIPT = "ukiyo_e.tmux"
TEMPLATE_NAMES = ("colors.conf.tmpl", "status.conf.tmpl")
HEADER = ("# GENERATED by configure.py from palette.toml."
          " Do not edit by hand.")


@dataclass(frozen=True)
class Template:
    """One tmux/*.conf.tmpl file: its name and text."""

    name: str
    text: str


@dataclass(frozen=True)
class ServerRef:
    """Whether the REQ-LIVE-2 server is reachable, and why not."""

    available: bool
    reason: str | None


def validate_roles(names, roles=TMUX_ROLES) -> list:
    """REQ-MAP-3 for TMUX_ROLES."""
    return check_role_map(MODULE, "TMUX_ROLES", roles, ROLE_KEYS, names)


def template_line_errors(name, number, line, roles) -> list:
    """REQ-MAP-4 for one template line."""
    errors = []
    for match in PLACEHOLDER.finditer(line):
        if match.group(1) not in roles:
            errors.append(ValidationError(
                tmpl_addr(name, number),
                f'unknown role "{match.group(0)}"'))
    if HEX_LITERAL.search(line):
        errors.append(ValidationError(tmpl_addr(name, number),
                                      "hex literal (use a {{role}})"))
    return errors


def validate_templates(templates, roles=TMUX_ROLES) -> list:
    """REQ-MAP-4: every placeholder names a role; no hex."""
    errors = []
    for template in templates:
        lines = template.text.splitlines()
        for number, line in enumerate(lines, 1):
            errors += template_line_errors(template.name, number, line,
                                           roles)
    return errors


def read_source(path) -> bytes:
    try:
        return path.read_bytes()
    except OSError as exc:
        raise InputError(f"{path}: cannot read: {exc.strerror}")


def load_templates(repo) -> tuple:
    """Read the two templates from <repo>/tmux/."""
    folder = repo / "tmux"
    return tuple(Template(name, read_source(folder / name).decode())
                 for name in TEMPLATE_NAMES)


def fill(template: Template, palette: Palette) -> bytes:
    """Replace every {{role}} by its lowercase hex; add the header."""
    def colour(match):
        return resolve(palette, TMUX_ROLES[match.group(1)])

    body = PLACEHOLDER.sub(colour, template.text)
    return f"{HEADER}\n{body}".encode("utf-8")


def render(palette: Palette, templates) -> dict:
    """The rendered tmux/*.conf files, keyed by install relpath."""
    return {"tmux/" + t.name.removesuffix(".tmpl"):
            FileSpec(fill(t, palette)) for t in templates}


def file_set(repo, palette: Palette, templates) -> dict:
    """The tmux subtree: the entry script and the rendered files."""
    tree = render(palette, templates)
    script = read_source(repo / "tmux" / SCRIPT)
    tree[SCRIPT] = FileSpec(script, EXEC_MODE)
    return tree


def command(argv) -> subprocess.CompletedProcess:
    """Run a command in the configurator's own environment."""
    return subprocess.run(argv, capture_output=True, text=True,
                          stdin=subprocess.DEVNULL, check=False)


def tmux(*args) -> subprocess.CompletedProcess:
    """A plain tmux client command: never -L or -S (SAF-6)."""
    return command(["tmux", *args])


def first_line(proc: subprocess.CompletedProcess) -> str:
    lines = (proc.stderr or proc.stdout).strip().splitlines()
    return lines[0] if lines else f"exit status {proc.returncode}"


def probe_server() -> ServerRef:
    """REQ-LIVE-2: running iff `tmux list-sessions` exits 0."""
    if shutil.which("tmux") is None:
        return ServerRef(False, "tmux not found")
    if tmux("list-sessions").returncode != 0:
        return ServerRef(False, "no server running")
    return ServerRef(True, None)


def reload(install) -> str | None:
    """REQ-LIVE-3: run the installed entry script; failure note."""
    proc = command([str(install / SCRIPT)])
    if proc.returncode != 0:
        return f"reload: {first_line(proc)}"
    return None


def reset_options() -> tuple:
    """REQ-UNI-2: styles; status options only if content was set."""
    shown = tmux("show-options", "-gqv", "@ukiyo_e_status_time")
    if shown.stdout.strip():
        return STYLE_OPTIONS + STATUS_OPTIONS + PRIVATE_OPTIONS
    return STYLE_OPTIONS


def reset() -> str | None:
    """REQ-UNI-2: unset theme-owned options; failure note."""
    for option in reset_options():
        proc = tmux("set-option", "-gu", option)
        if proc.returncode != 0:
            return f"reset: {first_line(proc)}"
    return None
